/**
 * Byte-exact cross-checks of the JCS canonicalizer + projections against
 * ground truth generated by the Rust source of truth (private-ai-gateway
 * @975ac50). `vectors.json` is the verbatim output of
 * `examples/gen_aci_vectors.rs`; every hex here was produced by the reference
 * `canonicalize` / digest code, so equality proves the TS port is byte-exact.
 */
import { describe, it, expect } from 'vitest'
import { bytesToHex } from '@noble/hashes/utils.js'
import {
  canonicalize,
  sha256Hex,
  jcsSha256Hex,
  jcsSha256Raw,
  publicKeyMaterialCanonical,
  workloadKeysetCanonical,
  keysetEndorsementPayloadCanonical,
  attestationStatementCanonical,
  canonicalBytesForSigning,
  type CanonicalValue,
} from '../jcs'
import vectors from './vectors.json'

const hex = (b: Uint8Array) => bytesToHex(b)

describe('canonicalize — Rust ground-truth vectors', () => {
  for (const c of vectors.canonical) {
    // The big-int vector cannot round-trip through JSON.parse (it exceeds
    // Number.MAX_SAFE_INTEGER); it is asserted separately with a BigInt input.
    if (c.desc === 'i64 and u64') continue
    it(`byte-exact: ${c.desc}`, () => {
      const bytes = canonicalize(c.input as CanonicalValue)
      expect(hex(bytes)).toBe(c.canonicalHex)
      expect(sha256Hex(bytes)).toBe(c.sha256Hex)
    })
  }

  it('i64 / u64 (BigInt) — 9007199254740993 serialises exactly', () => {
    const vec = vectors.canonical.find((c) => c.desc === 'i64 and u64')!
    // Rebuild the value with a BigInt so JS represents 2^53+1 exactly.
    const bytes = canonicalize({ big: 9007199254740993n, neg: -42 })
    expect(hex(bytes)).toBe(vec.canonicalHex)
  })

  it('rejects non-integer floats', () => {
    expect(() => canonicalize({ x: 1.5 } as unknown as CanonicalValue)).toThrow()
  })
})

describe('sha256Hex helper', () => {
  it('carries the "sha256:" prefix and 64 hex chars', () => {
    const out = sha256Hex(new Uint8Array([1, 2, 3]))
    expect(out.startsWith('sha256:')).toBe(true)
    expect(out.length).toBe('sha256:'.length + 64)
  })
})

describe('projections vs Rust to_canonical_value', () => {
  const report = vectors.report
  const keyset = report.attestation.workload_keyset

  it('workload_id = jcs_sha256_hex(identity.public_key)', () => {
    const pk = keyset.workload_identity.public_key
    expect(jcsSha256Hex(publicKeyMaterialCanonical(pk))).toBe(vectors.workloadId)
  })

  it('workload_keyset canonical bytes match', () => {
    expect(hex(canonicalize(workloadKeysetCanonical(keyset)))).toBe(vectors.keysetCanonicalHex)
  })

  it('workload_keyset_digest = jcs_sha256_hex(keyset)', () => {
    expect(jcsSha256Hex(workloadKeysetCanonical(keyset))).toBe(vectors.keysetDigest)
  })

  it('attestation statement canonical bytes match (nonce present)', () => {
    const val = attestationStatementCanonical(vectors.workloadId, vectors.keysetDigest, vectors.nonce)
    expect(hex(canonicalize(val))).toBe(vectors.statementCanonicalHex)
  })

  it('report_data (raw 32 bytes) matches — nonce present', () => {
    const val = attestationStatementCanonical(vectors.workloadId, vectors.keysetDigest, vectors.nonce)
    expect(hex(jcsSha256Raw(val))).toBe(vectors.reportDataHex)
  })

  it('report_data with absent nonce (null-included) matches', () => {
    const val = attestationStatementCanonical(vectors.workloadId, vectors.keysetDigest, undefined)
    expect(hex(jcsSha256Raw(val))).toBe(vectors.reportDataNoNonceHex)
  })

  it('keyset endorsement payload canonical bytes match', () => {
    const bytes = canonicalize(keysetEndorsementPayloadCanonical(vectors.keysetDigest))
    expect(hex(bytes)).toBe(vectors.endorsementPayloadHex)
  })
})

describe('receipt canonical_bytes_for_signing', () => {
  for (const r of vectors.receipts) {
    it(`byte-exact for ${r.algo} receipt (${r.keyId})`, () => {
      expect(hex(canonicalBytesForSigning(r.receipt as never))).toBe(r.canonicalForSigningHex)
    })
  }
})
