// Code generated by ent, DO NOT EDIT.

package billingsubject

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldDeletedAt, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldType, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldUserID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldTeamID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldStatus, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalance, v))
}

// TotalRecharged applies equality check predicate on the "total_recharged" field. It's identical to TotalRechargedEQ.
func TotalRecharged(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldTotalRecharged, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldConcurrency, v))
}

// RpmLimit applies equality check predicate on the "rpm_limit" field. It's identical to RpmLimitEQ.
func RpmLimit(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldRpmLimit, v))
}

// BalanceNotifyEnabled applies equality check predicate on the "balance_notify_enabled" field. It's identical to BalanceNotifyEnabledEQ.
func BalanceNotifyEnabled(v bool) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyEnabled, v))
}

// BalanceNotifyThresholdType applies equality check predicate on the "balance_notify_threshold_type" field. It's identical to BalanceNotifyThresholdTypeEQ.
func BalanceNotifyThresholdType(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThreshold applies equality check predicate on the "balance_notify_threshold" field. It's identical to BalanceNotifyThresholdEQ.
func BalanceNotifyThreshold(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyExtraEmails applies equality check predicate on the "balance_notify_extra_emails" field. It's identical to BalanceNotifyExtraEmailsEQ.
func BalanceNotifyExtraEmails(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyExtraEmails, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotNull(FieldDeletedAt))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContainsFold(FieldType, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotNull(FieldUserID))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldTeamID, vs...))
}

// TeamIDIsNil applies the IsNil predicate on the "team_id" field.
func TeamIDIsNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIsNull(FieldTeamID))
}

// TeamIDNotNil applies the NotNil predicate on the "team_id" field.
func TeamIDNotNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotNull(FieldTeamID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContainsFold(FieldStatus, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldBalance, v))
}

// TotalRechargedEQ applies the EQ predicate on the "total_recharged" field.
func TotalRechargedEQ(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldTotalRecharged, v))
}

// TotalRechargedNEQ applies the NEQ predicate on the "total_recharged" field.
func TotalRechargedNEQ(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldTotalRecharged, v))
}

// TotalRechargedIn applies the In predicate on the "total_recharged" field.
func TotalRechargedIn(vs ...float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldTotalRecharged, vs...))
}

// TotalRechargedNotIn applies the NotIn predicate on the "total_recharged" field.
func TotalRechargedNotIn(vs ...float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldTotalRecharged, vs...))
}

// TotalRechargedGT applies the GT predicate on the "total_recharged" field.
func TotalRechargedGT(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldTotalRecharged, v))
}

// TotalRechargedGTE applies the GTE predicate on the "total_recharged" field.
func TotalRechargedGTE(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldTotalRecharged, v))
}

// TotalRechargedLT applies the LT predicate on the "total_recharged" field.
func TotalRechargedLT(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldTotalRecharged, v))
}

// TotalRechargedLTE applies the LTE predicate on the "total_recharged" field.
func TotalRechargedLTE(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldTotalRecharged, v))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldConcurrency, v))
}

// RpmLimitEQ applies the EQ predicate on the "rpm_limit" field.
func RpmLimitEQ(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldRpmLimit, v))
}

// RpmLimitNEQ applies the NEQ predicate on the "rpm_limit" field.
func RpmLimitNEQ(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldRpmLimit, v))
}

// RpmLimitIn applies the In predicate on the "rpm_limit" field.
func RpmLimitIn(vs ...int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldRpmLimit, vs...))
}

// RpmLimitNotIn applies the NotIn predicate on the "rpm_limit" field.
func RpmLimitNotIn(vs ...int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldRpmLimit, vs...))
}

// RpmLimitGT applies the GT predicate on the "rpm_limit" field.
func RpmLimitGT(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldRpmLimit, v))
}

// RpmLimitGTE applies the GTE predicate on the "rpm_limit" field.
func RpmLimitGTE(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldRpmLimit, v))
}

// RpmLimitLT applies the LT predicate on the "rpm_limit" field.
func RpmLimitLT(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldRpmLimit, v))
}

// RpmLimitLTE applies the LTE predicate on the "rpm_limit" field.
func RpmLimitLTE(v int) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldRpmLimit, v))
}

// BalanceNotifyEnabledEQ applies the EQ predicate on the "balance_notify_enabled" field.
func BalanceNotifyEnabledEQ(v bool) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyEnabled, v))
}

// BalanceNotifyEnabledNEQ applies the NEQ predicate on the "balance_notify_enabled" field.
func BalanceNotifyEnabledNEQ(v bool) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldBalanceNotifyEnabled, v))
}

// BalanceNotifyThresholdTypeEQ applies the EQ predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeNEQ applies the NEQ predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeNEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeIn applies the In predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldBalanceNotifyThresholdType, vs...))
}

// BalanceNotifyThresholdTypeNotIn applies the NotIn predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeNotIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldBalanceNotifyThresholdType, vs...))
}

// BalanceNotifyThresholdTypeGT applies the GT predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeGT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeGTE applies the GTE predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeGTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeLT applies the LT predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeLT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeLTE applies the LTE predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeLTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeContains applies the Contains predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeContains(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContains(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeHasPrefix applies the HasPrefix predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeHasPrefix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasPrefix(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeHasSuffix applies the HasSuffix predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeHasSuffix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasSuffix(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeEqualFold applies the EqualFold predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeEqualFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEqualFold(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdTypeContainsFold applies the ContainsFold predicate on the "balance_notify_threshold_type" field.
func BalanceNotifyThresholdTypeContainsFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContainsFold(FieldBalanceNotifyThresholdType, v))
}

// BalanceNotifyThresholdEQ applies the EQ predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdEQ(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyThresholdNEQ applies the NEQ predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdNEQ(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyThresholdIn applies the In predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdIn(vs ...float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldBalanceNotifyThreshold, vs...))
}

// BalanceNotifyThresholdNotIn applies the NotIn predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdNotIn(vs ...float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldBalanceNotifyThreshold, vs...))
}

// BalanceNotifyThresholdGT applies the GT predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdGT(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyThresholdGTE applies the GTE predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdGTE(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyThresholdLT applies the LT predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdLT(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyThresholdLTE applies the LTE predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdLTE(v float64) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldBalanceNotifyThreshold, v))
}

// BalanceNotifyThresholdIsNil applies the IsNil predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdIsNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIsNull(FieldBalanceNotifyThreshold))
}

// BalanceNotifyThresholdNotNil applies the NotNil predicate on the "balance_notify_threshold" field.
func BalanceNotifyThresholdNotNil() predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotNull(FieldBalanceNotifyThreshold))
}

// BalanceNotifyExtraEmailsEQ applies the EQ predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEQ(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsNEQ applies the NEQ predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsNEQ(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNEQ(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsIn applies the In predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldIn(FieldBalanceNotifyExtraEmails, vs...))
}

// BalanceNotifyExtraEmailsNotIn applies the NotIn predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsNotIn(vs ...string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldNotIn(FieldBalanceNotifyExtraEmails, vs...))
}

// BalanceNotifyExtraEmailsGT applies the GT predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsGT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGT(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsGTE applies the GTE predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsGTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldGTE(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsLT applies the LT predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsLT(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLT(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsLTE applies the LTE predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsLTE(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldLTE(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsContains applies the Contains predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsContains(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContains(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsHasPrefix applies the HasPrefix predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsHasPrefix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasPrefix(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsHasSuffix applies the HasSuffix predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsHasSuffix(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldHasSuffix(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsEqualFold applies the EqualFold predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsEqualFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldEqualFold(FieldBalanceNotifyExtraEmails, v))
}

// BalanceNotifyExtraEmailsContainsFold applies the ContainsFold predicate on the "balance_notify_extra_emails" field.
func BalanceNotifyExtraEmailsContainsFold(v string) predicate.BillingSubject {
	return predicate.BillingSubject(sql.FieldContainsFold(FieldBalanceNotifyExtraEmails, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeams applies the HasEdge predicate on the "teams" edge.
func HasTeams() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TeamsTable, TeamsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamsWith applies the HasEdge predicate on the "teams" edge with a given conditions (other predicates).
func HasTeamsWith(preds ...predicate.Team) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newTeamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentOrders applies the HasEdge predicate on the "payment_orders" edge.
func HasPaymentOrders() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentOrdersTable, PaymentOrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentOrdersWith applies the HasEdge predicate on the "payment_orders" edge with a given conditions (other predicates).
func HasPaymentOrdersWith(preds ...predicate.PaymentOrder) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newPaymentOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.UserSubscription) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlatformQuotas applies the HasEdge predicate on the "platform_quotas" edge.
func HasPlatformQuotas() predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlatformQuotasTable, PlatformQuotasColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlatformQuotasWith applies the HasEdge predicate on the "platform_quotas" edge with a given conditions (other predicates).
func HasPlatformQuotasWith(preds ...predicate.UserPlatformQuota) predicate.BillingSubject {
	return predicate.BillingSubject(func(s *sql.Selector) {
		step := newPlatformQuotasStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingSubject) predicate.BillingSubject {
	return predicate.BillingSubject(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingSubject) predicate.BillingSubject {
	return predicate.BillingSubject(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingSubject) predicate.BillingSubject {
	return predicate.BillingSubject(sql.NotPredicates(p))
}
