// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/billingsubject"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BillingSubject is the model entity for the BillingSubject schema.
type BillingSubject struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID *int64 `json:"team_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// TotalRecharged holds the value of the "total_recharged" field.
	TotalRecharged float64 `json:"total_recharged,omitempty"`
	// Concurrency holds the value of the "concurrency" field.
	Concurrency int `json:"concurrency,omitempty"`
	// RpmLimit holds the value of the "rpm_limit" field.
	RpmLimit int `json:"rpm_limit,omitempty"`
	// BalanceNotifyEnabled holds the value of the "balance_notify_enabled" field.
	BalanceNotifyEnabled bool `json:"balance_notify_enabled,omitempty"`
	// BalanceNotifyThresholdType holds the value of the "balance_notify_threshold_type" field.
	BalanceNotifyThresholdType string `json:"balance_notify_threshold_type,omitempty"`
	// BalanceNotifyThreshold holds the value of the "balance_notify_threshold" field.
	BalanceNotifyThreshold *float64 `json:"balance_notify_threshold,omitempty"`
	// BalanceNotifyExtraEmails holds the value of the "balance_notify_extra_emails" field.
	BalanceNotifyExtraEmails string `json:"balance_notify_extra_emails,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillingSubjectQuery when eager-loading is set.
	Edges        BillingSubjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillingSubjectEdges holds the relations/edges for other nodes in the graph.
type BillingSubjectEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// Teams holds the value of the teams edge.
	Teams []*Team `json:"teams,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// PaymentOrders holds the value of the payment_orders edge.
	PaymentOrders []*PaymentOrder `json:"payment_orders,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*UserSubscription `json:"subscriptions,omitempty"`
	// PlatformQuotas holds the value of the platform_quotas edge.
	PlatformQuotas []*UserPlatformQuota `json:"platform_quotas,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingSubjectEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillingSubjectEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// TeamsOrErr returns the Teams value or an error if the edge
// was not loaded in eager-loading.
func (e BillingSubjectEdges) TeamsOrErr() ([]*Team, error) {
	if e.loadedTypes[2] {
		return e.Teams, nil
	}
	return nil, &NotLoadedError{edge: "teams"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e BillingSubjectEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[3] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e BillingSubjectEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[4] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// PaymentOrdersOrErr returns the PaymentOrders value or an error if the edge
// was not loaded in eager-loading.
func (e BillingSubjectEdges) PaymentOrdersOrErr() ([]*PaymentOrder, error) {
	if e.loadedTypes[5] {
		return e.PaymentOrders, nil
	}
	return nil, &NotLoadedError{edge: "payment_orders"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e BillingSubjectEdges) SubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[6] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// PlatformQuotasOrErr returns the PlatformQuotas value or an error if the edge
// was not loaded in eager-loading.
func (e BillingSubjectEdges) PlatformQuotasOrErr() ([]*UserPlatformQuota, error) {
	if e.loadedTypes[7] {
		return e.PlatformQuotas, nil
	}
	return nil, &NotLoadedError{edge: "platform_quotas"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingSubject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billingsubject.FieldBalanceNotifyEnabled:
			values[i] = new(sql.NullBool)
		case billingsubject.FieldBalance, billingsubject.FieldTotalRecharged, billingsubject.FieldBalanceNotifyThreshold:
			values[i] = new(sql.NullFloat64)
		case billingsubject.FieldID, billingsubject.FieldUserID, billingsubject.FieldTeamID, billingsubject.FieldConcurrency, billingsubject.FieldRpmLimit:
			values[i] = new(sql.NullInt64)
		case billingsubject.FieldType, billingsubject.FieldStatus, billingsubject.FieldBalanceNotifyThresholdType, billingsubject.FieldBalanceNotifyExtraEmails:
			values[i] = new(sql.NullString)
		case billingsubject.FieldCreatedAt, billingsubject.FieldUpdatedAt, billingsubject.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingSubject fields.
func (_m *BillingSubject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billingsubject.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case billingsubject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billingsubject.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case billingsubject.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case billingsubject.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case billingsubject.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case billingsubject.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = new(int64)
				*_m.TeamID = value.Int64
			}
		case billingsubject.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case billingsubject.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case billingsubject.FieldTotalRecharged:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_recharged", values[i])
			} else if value.Valid {
				_m.TotalRecharged = value.Float64
			}
		case billingsubject.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case billingsubject.FieldRpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm_limit", values[i])
			} else if value.Valid {
				_m.RpmLimit = int(value.Int64)
			}
		case billingsubject.FieldBalanceNotifyEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field balance_notify_enabled", values[i])
			} else if value.Valid {
				_m.BalanceNotifyEnabled = value.Bool
			}
		case billingsubject.FieldBalanceNotifyThresholdType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_notify_threshold_type", values[i])
			} else if value.Valid {
				_m.BalanceNotifyThresholdType = value.String
			}
		case billingsubject.FieldBalanceNotifyThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_notify_threshold", values[i])
			} else if value.Valid {
				_m.BalanceNotifyThreshold = new(float64)
				*_m.BalanceNotifyThreshold = value.Float64
			}
		case billingsubject.FieldBalanceNotifyExtraEmails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_notify_extra_emails", values[i])
			} else if value.Valid {
				_m.BalanceNotifyExtraEmails = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingSubject.
// This includes values selected through modifiers, order, etc.
func (_m *BillingSubject) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryUser() *UserQuery {
	return NewBillingSubjectClient(_m.config).QueryUser(_m)
}

// QueryTeam queries the "team" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryTeam() *TeamQuery {
	return NewBillingSubjectClient(_m.config).QueryTeam(_m)
}

// QueryTeams queries the "teams" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryTeams() *TeamQuery {
	return NewBillingSubjectClient(_m.config).QueryTeams(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryAPIKeys() *APIKeyQuery {
	return NewBillingSubjectClient(_m.config).QueryAPIKeys(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryUsageLogs() *UsageLogQuery {
	return NewBillingSubjectClient(_m.config).QueryUsageLogs(_m)
}

// QueryPaymentOrders queries the "payment_orders" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryPaymentOrders() *PaymentOrderQuery {
	return NewBillingSubjectClient(_m.config).QueryPaymentOrders(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the BillingSubject entity.
func (_m *BillingSubject) QuerySubscriptions() *UserSubscriptionQuery {
	return NewBillingSubjectClient(_m.config).QuerySubscriptions(_m)
}

// QueryPlatformQuotas queries the "platform_quotas" edge of the BillingSubject entity.
func (_m *BillingSubject) QueryPlatformQuotas() *UserPlatformQuotaQuery {
	return NewBillingSubjectClient(_m.config).QueryPlatformQuotas(_m)
}

// Update returns a builder for updating this BillingSubject.
// Note that you need to call BillingSubject.Unwrap() before calling this method if this BillingSubject
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillingSubject) Update() *BillingSubjectUpdateOne {
	return NewBillingSubjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillingSubject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillingSubject) Unwrap() *BillingSubject {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillingSubject is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillingSubject) String() string {
	var builder strings.Builder
	builder.WriteString("BillingSubject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TeamID; v != nil {
		builder.WriteString("team_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("total_recharged=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRecharged))
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("rpm_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RpmLimit))
	builder.WriteString(", ")
	builder.WriteString("balance_notify_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceNotifyEnabled))
	builder.WriteString(", ")
	builder.WriteString("balance_notify_threshold_type=")
	builder.WriteString(_m.BalanceNotifyThresholdType)
	builder.WriteString(", ")
	if v := _m.BalanceNotifyThreshold; v != nil {
		builder.WriteString("balance_notify_threshold=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("balance_notify_extra_emails=")
	builder.WriteString(_m.BalanceNotifyExtraEmails)
	builder.WriteByte(')')
	return builder.String()
}

// BillingSubjects is a parsable slice of BillingSubject.
type BillingSubjects []*BillingSubject
