// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/billingsubject"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userplatformquota"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// BillingSubjectUpdate is the builder for updating BillingSubject entities.
type BillingSubjectUpdate struct {
	config
	hooks    []Hook
	mutation *BillingSubjectMutation
}

// Where appends a list predicates to the BillingSubjectUpdate builder.
func (_u *BillingSubjectUpdate) Where(ps ...predicate.BillingSubject) *BillingSubjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingSubjectUpdate) SetUpdatedAt(v time.Time) *BillingSubjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BillingSubjectUpdate) SetDeletedAt(v time.Time) *BillingSubjectUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableDeletedAt(v *time.Time) *BillingSubjectUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BillingSubjectUpdate) ClearDeletedAt() *BillingSubjectUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetType sets the "type" field.
func (_u *BillingSubjectUpdate) SetType(v string) *BillingSubjectUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableType(v *string) *BillingSubjectUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BillingSubjectUpdate) SetUserID(v int64) *BillingSubjectUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableUserID(v *int64) *BillingSubjectUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *BillingSubjectUpdate) ClearUserID() *BillingSubjectUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *BillingSubjectUpdate) SetTeamID(v int64) *BillingSubjectUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableTeamID(v *int64) *BillingSubjectUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *BillingSubjectUpdate) ClearTeamID() *BillingSubjectUpdate {
	_u.mutation.ClearTeamID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BillingSubjectUpdate) SetStatus(v string) *BillingSubjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableStatus(v *string) *BillingSubjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *BillingSubjectUpdate) SetBalance(v float64) *BillingSubjectUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableBalance(v *float64) *BillingSubjectUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *BillingSubjectUpdate) AddBalance(v float64) *BillingSubjectUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetTotalRecharged sets the "total_recharged" field.
func (_u *BillingSubjectUpdate) SetTotalRecharged(v float64) *BillingSubjectUpdate {
	_u.mutation.ResetTotalRecharged()
	_u.mutation.SetTotalRecharged(v)
	return _u
}

// SetNillableTotalRecharged sets the "total_recharged" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableTotalRecharged(v *float64) *BillingSubjectUpdate {
	if v != nil {
		_u.SetTotalRecharged(*v)
	}
	return _u
}

// AddTotalRecharged adds value to the "total_recharged" field.
func (_u *BillingSubjectUpdate) AddTotalRecharged(v float64) *BillingSubjectUpdate {
	_u.mutation.AddTotalRecharged(v)
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *BillingSubjectUpdate) SetConcurrency(v int) *BillingSubjectUpdate {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableConcurrency(v *int) *BillingSubjectUpdate {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *BillingSubjectUpdate) AddConcurrency(v int) *BillingSubjectUpdate {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *BillingSubjectUpdate) SetRpmLimit(v int) *BillingSubjectUpdate {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableRpmLimit(v *int) *BillingSubjectUpdate {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *BillingSubjectUpdate) AddRpmLimit(v int) *BillingSubjectUpdate {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetBalanceNotifyEnabled sets the "balance_notify_enabled" field.
func (_u *BillingSubjectUpdate) SetBalanceNotifyEnabled(v bool) *BillingSubjectUpdate {
	_u.mutation.SetBalanceNotifyEnabled(v)
	return _u
}

// SetNillableBalanceNotifyEnabled sets the "balance_notify_enabled" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableBalanceNotifyEnabled(v *bool) *BillingSubjectUpdate {
	if v != nil {
		_u.SetBalanceNotifyEnabled(*v)
	}
	return _u
}

// SetBalanceNotifyThresholdType sets the "balance_notify_threshold_type" field.
func (_u *BillingSubjectUpdate) SetBalanceNotifyThresholdType(v string) *BillingSubjectUpdate {
	_u.mutation.SetBalanceNotifyThresholdType(v)
	return _u
}

// SetNillableBalanceNotifyThresholdType sets the "balance_notify_threshold_type" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableBalanceNotifyThresholdType(v *string) *BillingSubjectUpdate {
	if v != nil {
		_u.SetBalanceNotifyThresholdType(*v)
	}
	return _u
}

// SetBalanceNotifyThreshold sets the "balance_notify_threshold" field.
func (_u *BillingSubjectUpdate) SetBalanceNotifyThreshold(v float64) *BillingSubjectUpdate {
	_u.mutation.ResetBalanceNotifyThreshold()
	_u.mutation.SetBalanceNotifyThreshold(v)
	return _u
}

// SetNillableBalanceNotifyThreshold sets the "balance_notify_threshold" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableBalanceNotifyThreshold(v *float64) *BillingSubjectUpdate {
	if v != nil {
		_u.SetBalanceNotifyThreshold(*v)
	}
	return _u
}

// AddBalanceNotifyThreshold adds value to the "balance_notify_threshold" field.
func (_u *BillingSubjectUpdate) AddBalanceNotifyThreshold(v float64) *BillingSubjectUpdate {
	_u.mutation.AddBalanceNotifyThreshold(v)
	return _u
}

// ClearBalanceNotifyThreshold clears the value of the "balance_notify_threshold" field.
func (_u *BillingSubjectUpdate) ClearBalanceNotifyThreshold() *BillingSubjectUpdate {
	_u.mutation.ClearBalanceNotifyThreshold()
	return _u
}

// SetBalanceNotifyExtraEmails sets the "balance_notify_extra_emails" field.
func (_u *BillingSubjectUpdate) SetBalanceNotifyExtraEmails(v string) *BillingSubjectUpdate {
	_u.mutation.SetBalanceNotifyExtraEmails(v)
	return _u
}

// SetNillableBalanceNotifyExtraEmails sets the "balance_notify_extra_emails" field if the given value is not nil.
func (_u *BillingSubjectUpdate) SetNillableBalanceNotifyExtraEmails(v *string) *BillingSubjectUpdate {
	if v != nil {
		_u.SetBalanceNotifyExtraEmails(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BillingSubjectUpdate) SetUser(v *User) *BillingSubjectUpdate {
	return _u.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *BillingSubjectUpdate) SetTeam(v *Team) *BillingSubjectUpdate {
	return _u.SetTeamID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *BillingSubjectUpdate) AddTeamIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *BillingSubjectUpdate) AddTeams(v ...*Team) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *BillingSubjectUpdate) AddAPIKeyIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *BillingSubjectUpdate) AddAPIKeys(v ...*APIKey) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *BillingSubjectUpdate) AddUsageLogIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *BillingSubjectUpdate) AddUsageLogs(v ...*UsageLog) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// AddPaymentOrderIDs adds the "payment_orders" edge to the PaymentOrder entity by IDs.
func (_u *BillingSubjectUpdate) AddPaymentOrderIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.AddPaymentOrderIDs(ids...)
	return _u
}

// AddPaymentOrders adds the "payment_orders" edges to the PaymentOrder entity.
func (_u *BillingSubjectUpdate) AddPaymentOrders(v ...*PaymentOrder) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentOrderIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *BillingSubjectUpdate) AddSubscriptionIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *BillingSubjectUpdate) AddSubscriptions(v ...*UserSubscription) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddPlatformQuotaIDs adds the "platform_quotas" edge to the UserPlatformQuota entity by IDs.
func (_u *BillingSubjectUpdate) AddPlatformQuotaIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.AddPlatformQuotaIDs(ids...)
	return _u
}

// AddPlatformQuotas adds the "platform_quotas" edges to the UserPlatformQuota entity.
func (_u *BillingSubjectUpdate) AddPlatformQuotas(v ...*UserPlatformQuota) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlatformQuotaIDs(ids...)
}

// Mutation returns the BillingSubjectMutation object of the builder.
func (_u *BillingSubjectUpdate) Mutation() *BillingSubjectMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BillingSubjectUpdate) ClearUser() *BillingSubjectUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *BillingSubjectUpdate) ClearTeam() *BillingSubjectUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *BillingSubjectUpdate) ClearTeams() *BillingSubjectUpdate {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *BillingSubjectUpdate) RemoveTeamIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *BillingSubjectUpdate) RemoveTeams(v ...*Team) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *BillingSubjectUpdate) ClearAPIKeys() *BillingSubjectUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *BillingSubjectUpdate) RemoveAPIKeyIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *BillingSubjectUpdate) RemoveAPIKeys(v ...*APIKey) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *BillingSubjectUpdate) ClearUsageLogs() *BillingSubjectUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *BillingSubjectUpdate) RemoveUsageLogIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *BillingSubjectUpdate) RemoveUsageLogs(v ...*UsageLog) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// ClearPaymentOrders clears all "payment_orders" edges to the PaymentOrder entity.
func (_u *BillingSubjectUpdate) ClearPaymentOrders() *BillingSubjectUpdate {
	_u.mutation.ClearPaymentOrders()
	return _u
}

// RemovePaymentOrderIDs removes the "payment_orders" edge to PaymentOrder entities by IDs.
func (_u *BillingSubjectUpdate) RemovePaymentOrderIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.RemovePaymentOrderIDs(ids...)
	return _u
}

// RemovePaymentOrders removes "payment_orders" edges to PaymentOrder entities.
func (_u *BillingSubjectUpdate) RemovePaymentOrders(v ...*PaymentOrder) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentOrderIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *BillingSubjectUpdate) ClearSubscriptions() *BillingSubjectUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *BillingSubjectUpdate) RemoveSubscriptionIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *BillingSubjectUpdate) RemoveSubscriptions(v ...*UserSubscription) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearPlatformQuotas clears all "platform_quotas" edges to the UserPlatformQuota entity.
func (_u *BillingSubjectUpdate) ClearPlatformQuotas() *BillingSubjectUpdate {
	_u.mutation.ClearPlatformQuotas()
	return _u
}

// RemovePlatformQuotaIDs removes the "platform_quotas" edge to UserPlatformQuota entities by IDs.
func (_u *BillingSubjectUpdate) RemovePlatformQuotaIDs(ids ...int64) *BillingSubjectUpdate {
	_u.mutation.RemovePlatformQuotaIDs(ids...)
	return _u
}

// RemovePlatformQuotas removes "platform_quotas" edges to UserPlatformQuota entities.
func (_u *BillingSubjectUpdate) RemovePlatformQuotas(v ...*UserPlatformQuota) *BillingSubjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlatformQuotaIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillingSubjectUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingSubjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillingSubjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingSubjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingSubjectUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if billingsubject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized billingsubject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := billingsubject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingSubjectUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := billingsubject.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BillingSubject.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := billingsubject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingSubject.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BillingSubjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingsubject.Table, billingsubject.Columns, sqlgraph.NewFieldSpec(billingsubject.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingsubject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(billingsubject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(billingsubject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(billingsubject.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(billingsubject.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(billingsubject.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(billingsubject.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRecharged(); ok {
		_spec.SetField(billingsubject.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalRecharged(); ok {
		_spec.AddField(billingsubject.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(billingsubject.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(billingsubject.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(billingsubject.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(billingsubject.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BalanceNotifyEnabled(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BalanceNotifyThresholdType(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyThresholdType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceNotifyThreshold(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceNotifyThreshold(); ok {
		_spec.AddField(billingsubject.FieldBalanceNotifyThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceNotifyThresholdCleared() {
		_spec.ClearField(billingsubject.FieldBalanceNotifyThreshold, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceNotifyExtraEmails(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyExtraEmails, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.UserTable,
			Columns: []string{billingsubject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.UserTable,
			Columns: []string{billingsubject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.TeamTable,
			Columns: []string{billingsubject.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.TeamTable,
			Columns: []string{billingsubject.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.TeamsTable,
			Columns: []string{billingsubject.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.TeamsTable,
			Columns: []string{billingsubject.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.TeamsTable,
			Columns: []string{billingsubject.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.APIKeysTable,
			Columns: []string{billingsubject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.APIKeysTable,
			Columns: []string{billingsubject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.APIKeysTable,
			Columns: []string{billingsubject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.UsageLogsTable,
			Columns: []string{billingsubject.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.UsageLogsTable,
			Columns: []string{billingsubject.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.UsageLogsTable,
			Columns: []string{billingsubject.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentOrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PaymentOrdersTable,
			Columns: []string{billingsubject.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentOrdersIDs(); len(nodes) > 0 && !_u.mutation.PaymentOrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PaymentOrdersTable,
			Columns: []string{billingsubject.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PaymentOrdersTable,
			Columns: []string{billingsubject.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.SubscriptionsTable,
			Columns: []string{billingsubject.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.SubscriptionsTable,
			Columns: []string{billingsubject.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.SubscriptionsTable,
			Columns: []string{billingsubject.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlatformQuotasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PlatformQuotasTable,
			Columns: []string{billingsubject.PlatformQuotasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userplatformquota.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlatformQuotasIDs(); len(nodes) > 0 && !_u.mutation.PlatformQuotasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PlatformQuotasTable,
			Columns: []string{billingsubject.PlatformQuotasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userplatformquota.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformQuotasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PlatformQuotasTable,
			Columns: []string{billingsubject.PlatformQuotasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userplatformquota.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingsubject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillingSubjectUpdateOne is the builder for updating a single BillingSubject entity.
type BillingSubjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillingSubjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingSubjectUpdateOne) SetUpdatedAt(v time.Time) *BillingSubjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BillingSubjectUpdateOne) SetDeletedAt(v time.Time) *BillingSubjectUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableDeletedAt(v *time.Time) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BillingSubjectUpdateOne) ClearDeletedAt() *BillingSubjectUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetType sets the "type" field.
func (_u *BillingSubjectUpdateOne) SetType(v string) *BillingSubjectUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableType(v *string) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BillingSubjectUpdateOne) SetUserID(v int64) *BillingSubjectUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableUserID(v *int64) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *BillingSubjectUpdateOne) ClearUserID() *BillingSubjectUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *BillingSubjectUpdateOne) SetTeamID(v int64) *BillingSubjectUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableTeamID(v *int64) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *BillingSubjectUpdateOne) ClearTeamID() *BillingSubjectUpdateOne {
	_u.mutation.ClearTeamID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BillingSubjectUpdateOne) SetStatus(v string) *BillingSubjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableStatus(v *string) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *BillingSubjectUpdateOne) SetBalance(v float64) *BillingSubjectUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableBalance(v *float64) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *BillingSubjectUpdateOne) AddBalance(v float64) *BillingSubjectUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetTotalRecharged sets the "total_recharged" field.
func (_u *BillingSubjectUpdateOne) SetTotalRecharged(v float64) *BillingSubjectUpdateOne {
	_u.mutation.ResetTotalRecharged()
	_u.mutation.SetTotalRecharged(v)
	return _u
}

// SetNillableTotalRecharged sets the "total_recharged" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableTotalRecharged(v *float64) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetTotalRecharged(*v)
	}
	return _u
}

// AddTotalRecharged adds value to the "total_recharged" field.
func (_u *BillingSubjectUpdateOne) AddTotalRecharged(v float64) *BillingSubjectUpdateOne {
	_u.mutation.AddTotalRecharged(v)
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *BillingSubjectUpdateOne) SetConcurrency(v int) *BillingSubjectUpdateOne {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableConcurrency(v *int) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *BillingSubjectUpdateOne) AddConcurrency(v int) *BillingSubjectUpdateOne {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *BillingSubjectUpdateOne) SetRpmLimit(v int) *BillingSubjectUpdateOne {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableRpmLimit(v *int) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *BillingSubjectUpdateOne) AddRpmLimit(v int) *BillingSubjectUpdateOne {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetBalanceNotifyEnabled sets the "balance_notify_enabled" field.
func (_u *BillingSubjectUpdateOne) SetBalanceNotifyEnabled(v bool) *BillingSubjectUpdateOne {
	_u.mutation.SetBalanceNotifyEnabled(v)
	return _u
}

// SetNillableBalanceNotifyEnabled sets the "balance_notify_enabled" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableBalanceNotifyEnabled(v *bool) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetBalanceNotifyEnabled(*v)
	}
	return _u
}

// SetBalanceNotifyThresholdType sets the "balance_notify_threshold_type" field.
func (_u *BillingSubjectUpdateOne) SetBalanceNotifyThresholdType(v string) *BillingSubjectUpdateOne {
	_u.mutation.SetBalanceNotifyThresholdType(v)
	return _u
}

// SetNillableBalanceNotifyThresholdType sets the "balance_notify_threshold_type" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableBalanceNotifyThresholdType(v *string) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetBalanceNotifyThresholdType(*v)
	}
	return _u
}

// SetBalanceNotifyThreshold sets the "balance_notify_threshold" field.
func (_u *BillingSubjectUpdateOne) SetBalanceNotifyThreshold(v float64) *BillingSubjectUpdateOne {
	_u.mutation.ResetBalanceNotifyThreshold()
	_u.mutation.SetBalanceNotifyThreshold(v)
	return _u
}

// SetNillableBalanceNotifyThreshold sets the "balance_notify_threshold" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableBalanceNotifyThreshold(v *float64) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetBalanceNotifyThreshold(*v)
	}
	return _u
}

// AddBalanceNotifyThreshold adds value to the "balance_notify_threshold" field.
func (_u *BillingSubjectUpdateOne) AddBalanceNotifyThreshold(v float64) *BillingSubjectUpdateOne {
	_u.mutation.AddBalanceNotifyThreshold(v)
	return _u
}

// ClearBalanceNotifyThreshold clears the value of the "balance_notify_threshold" field.
func (_u *BillingSubjectUpdateOne) ClearBalanceNotifyThreshold() *BillingSubjectUpdateOne {
	_u.mutation.ClearBalanceNotifyThreshold()
	return _u
}

// SetBalanceNotifyExtraEmails sets the "balance_notify_extra_emails" field.
func (_u *BillingSubjectUpdateOne) SetBalanceNotifyExtraEmails(v string) *BillingSubjectUpdateOne {
	_u.mutation.SetBalanceNotifyExtraEmails(v)
	return _u
}

// SetNillableBalanceNotifyExtraEmails sets the "balance_notify_extra_emails" field if the given value is not nil.
func (_u *BillingSubjectUpdateOne) SetNillableBalanceNotifyExtraEmails(v *string) *BillingSubjectUpdateOne {
	if v != nil {
		_u.SetBalanceNotifyExtraEmails(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BillingSubjectUpdateOne) SetUser(v *User) *BillingSubjectUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *BillingSubjectUpdateOne) SetTeam(v *Team) *BillingSubjectUpdateOne {
	return _u.SetTeamID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *BillingSubjectUpdateOne) AddTeamIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *BillingSubjectUpdateOne) AddTeams(v ...*Team) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *BillingSubjectUpdateOne) AddAPIKeyIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *BillingSubjectUpdateOne) AddAPIKeys(v ...*APIKey) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *BillingSubjectUpdateOne) AddUsageLogIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *BillingSubjectUpdateOne) AddUsageLogs(v ...*UsageLog) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// AddPaymentOrderIDs adds the "payment_orders" edge to the PaymentOrder entity by IDs.
func (_u *BillingSubjectUpdateOne) AddPaymentOrderIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.AddPaymentOrderIDs(ids...)
	return _u
}

// AddPaymentOrders adds the "payment_orders" edges to the PaymentOrder entity.
func (_u *BillingSubjectUpdateOne) AddPaymentOrders(v ...*PaymentOrder) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentOrderIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *BillingSubjectUpdateOne) AddSubscriptionIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *BillingSubjectUpdateOne) AddSubscriptions(v ...*UserSubscription) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddPlatformQuotaIDs adds the "platform_quotas" edge to the UserPlatformQuota entity by IDs.
func (_u *BillingSubjectUpdateOne) AddPlatformQuotaIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.AddPlatformQuotaIDs(ids...)
	return _u
}

// AddPlatformQuotas adds the "platform_quotas" edges to the UserPlatformQuota entity.
func (_u *BillingSubjectUpdateOne) AddPlatformQuotas(v ...*UserPlatformQuota) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlatformQuotaIDs(ids...)
}

// Mutation returns the BillingSubjectMutation object of the builder.
func (_u *BillingSubjectUpdateOne) Mutation() *BillingSubjectMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BillingSubjectUpdateOne) ClearUser() *BillingSubjectUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *BillingSubjectUpdateOne) ClearTeam() *BillingSubjectUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *BillingSubjectUpdateOne) ClearTeams() *BillingSubjectUpdateOne {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *BillingSubjectUpdateOne) RemoveTeamIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *BillingSubjectUpdateOne) RemoveTeams(v ...*Team) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *BillingSubjectUpdateOne) ClearAPIKeys() *BillingSubjectUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *BillingSubjectUpdateOne) RemoveAPIKeyIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *BillingSubjectUpdateOne) RemoveAPIKeys(v ...*APIKey) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *BillingSubjectUpdateOne) ClearUsageLogs() *BillingSubjectUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *BillingSubjectUpdateOne) RemoveUsageLogIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *BillingSubjectUpdateOne) RemoveUsageLogs(v ...*UsageLog) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// ClearPaymentOrders clears all "payment_orders" edges to the PaymentOrder entity.
func (_u *BillingSubjectUpdateOne) ClearPaymentOrders() *BillingSubjectUpdateOne {
	_u.mutation.ClearPaymentOrders()
	return _u
}

// RemovePaymentOrderIDs removes the "payment_orders" edge to PaymentOrder entities by IDs.
func (_u *BillingSubjectUpdateOne) RemovePaymentOrderIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.RemovePaymentOrderIDs(ids...)
	return _u
}

// RemovePaymentOrders removes "payment_orders" edges to PaymentOrder entities.
func (_u *BillingSubjectUpdateOne) RemovePaymentOrders(v ...*PaymentOrder) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentOrderIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *BillingSubjectUpdateOne) ClearSubscriptions() *BillingSubjectUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *BillingSubjectUpdateOne) RemoveSubscriptionIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *BillingSubjectUpdateOne) RemoveSubscriptions(v ...*UserSubscription) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearPlatformQuotas clears all "platform_quotas" edges to the UserPlatformQuota entity.
func (_u *BillingSubjectUpdateOne) ClearPlatformQuotas() *BillingSubjectUpdateOne {
	_u.mutation.ClearPlatformQuotas()
	return _u
}

// RemovePlatformQuotaIDs removes the "platform_quotas" edge to UserPlatformQuota entities by IDs.
func (_u *BillingSubjectUpdateOne) RemovePlatformQuotaIDs(ids ...int64) *BillingSubjectUpdateOne {
	_u.mutation.RemovePlatformQuotaIDs(ids...)
	return _u
}

// RemovePlatformQuotas removes "platform_quotas" edges to UserPlatformQuota entities.
func (_u *BillingSubjectUpdateOne) RemovePlatformQuotas(v ...*UserPlatformQuota) *BillingSubjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlatformQuotaIDs(ids...)
}

// Where appends a list predicates to the BillingSubjectUpdate builder.
func (_u *BillingSubjectUpdateOne) Where(ps ...predicate.BillingSubject) *BillingSubjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillingSubjectUpdateOne) Select(field string, fields ...string) *BillingSubjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillingSubject entity.
func (_u *BillingSubjectUpdateOne) Save(ctx context.Context) (*BillingSubject, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingSubjectUpdateOne) SaveX(ctx context.Context) *BillingSubject {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillingSubjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingSubjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingSubjectUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if billingsubject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized billingsubject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := billingsubject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingSubjectUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := billingsubject.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BillingSubject.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := billingsubject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingSubject.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BillingSubjectUpdateOne) sqlSave(ctx context.Context) (_node *BillingSubject, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingsubject.Table, billingsubject.Columns, sqlgraph.NewFieldSpec(billingsubject.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillingSubject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billingsubject.FieldID)
		for _, f := range fields {
			if !billingsubject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billingsubject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingsubject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(billingsubject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(billingsubject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(billingsubject.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(billingsubject.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(billingsubject.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(billingsubject.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRecharged(); ok {
		_spec.SetField(billingsubject.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalRecharged(); ok {
		_spec.AddField(billingsubject.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(billingsubject.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(billingsubject.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(billingsubject.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(billingsubject.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BalanceNotifyEnabled(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BalanceNotifyThresholdType(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyThresholdType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceNotifyThreshold(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceNotifyThreshold(); ok {
		_spec.AddField(billingsubject.FieldBalanceNotifyThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceNotifyThresholdCleared() {
		_spec.ClearField(billingsubject.FieldBalanceNotifyThreshold, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceNotifyExtraEmails(); ok {
		_spec.SetField(billingsubject.FieldBalanceNotifyExtraEmails, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.UserTable,
			Columns: []string{billingsubject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.UserTable,
			Columns: []string{billingsubject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.TeamTable,
			Columns: []string{billingsubject.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billingsubject.TeamTable,
			Columns: []string{billingsubject.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.TeamsTable,
			Columns: []string{billingsubject.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.TeamsTable,
			Columns: []string{billingsubject.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.TeamsTable,
			Columns: []string{billingsubject.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.APIKeysTable,
			Columns: []string{billingsubject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.APIKeysTable,
			Columns: []string{billingsubject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.APIKeysTable,
			Columns: []string{billingsubject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.UsageLogsTable,
			Columns: []string{billingsubject.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.UsageLogsTable,
			Columns: []string{billingsubject.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.UsageLogsTable,
			Columns: []string{billingsubject.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentOrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PaymentOrdersTable,
			Columns: []string{billingsubject.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentOrdersIDs(); len(nodes) > 0 && !_u.mutation.PaymentOrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PaymentOrdersTable,
			Columns: []string{billingsubject.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PaymentOrdersTable,
			Columns: []string{billingsubject.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.SubscriptionsTable,
			Columns: []string{billingsubject.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.SubscriptionsTable,
			Columns: []string{billingsubject.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.SubscriptionsTable,
			Columns: []string{billingsubject.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlatformQuotasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PlatformQuotasTable,
			Columns: []string{billingsubject.PlatformQuotasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userplatformquota.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlatformQuotasIDs(); len(nodes) > 0 && !_u.mutation.PlatformQuotasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PlatformQuotasTable,
			Columns: []string{billingsubject.PlatformQuotasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userplatformquota.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlatformQuotasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingsubject.PlatformQuotasTable,
			Columns: []string{billingsubject.PlatformQuotasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userplatformquota.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BillingSubject{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingsubject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
