// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemauditlog"
)

// RedeemAuditLogCreate is the builder for creating a RedeemAuditLog entity.
type RedeemAuditLogCreate struct {
	config
	mutation *RedeemAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemAuditLogCreate) SetRedeemCodeID(v int64) *RedeemAuditLogCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *RedeemAuditLogCreate) SetCode(v string) *RedeemAuditLogCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *RedeemAuditLogCreate) SetActorUserID(v int64) *RedeemAuditLogCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (_c *RedeemAuditLogCreate) SetBillingSubjectID(v int64) *RedeemAuditLogCreate {
	_c.mutation.SetBillingSubjectID(v)
	return _c
}

// SetNillableBillingSubjectID sets the "billing_subject_id" field if the given value is not nil.
func (_c *RedeemAuditLogCreate) SetNillableBillingSubjectID(v *int64) *RedeemAuditLogCreate {
	if v != nil {
		_c.SetBillingSubjectID(*v)
	}
	return _c
}

// SetCodeType sets the "code_type" field.
func (_c *RedeemAuditLogCreate) SetCodeType(v string) *RedeemAuditLogCreate {
	_c.mutation.SetCodeType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RedeemAuditLogCreate) SetAmount(v float64) *RedeemAuditLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *RedeemAuditLogCreate) SetNillableAmount(v *float64) *RedeemAuditLogCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RedeemAuditLogCreate) SetCreatedAt(v time.Time) *RedeemAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RedeemAuditLogCreate) SetNillableCreatedAt(v *time.Time) *RedeemAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the RedeemAuditLogMutation object of the builder.
func (_c *RedeemAuditLogCreate) Mutation() *RedeemAuditLogMutation {
	return _c.mutation
}

// Save creates the RedeemAuditLog in the database.
func (_c *RedeemAuditLogCreate) Save(ctx context.Context) (*RedeemAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemAuditLogCreate) SaveX(ctx context.Context) *RedeemAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemAuditLogCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := redeemauditlog.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := redeemauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemAuditLogCreate) check() error {
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "RedeemAuditLog.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "RedeemAuditLog.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := redeemauditlog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RedeemAuditLog.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorUserID(); !ok {
		return &ValidationError{Name: "actor_user_id", err: errors.New(`ent: missing required field "RedeemAuditLog.actor_user_id"`)}
	}
	if _, ok := _c.mutation.CodeType(); !ok {
		return &ValidationError{Name: "code_type", err: errors.New(`ent: missing required field "RedeemAuditLog.code_type"`)}
	}
	if v, ok := _c.mutation.CodeType(); ok {
		if err := redeemauditlog.CodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "code_type", err: fmt.Errorf(`ent: validator failed for field "RedeemAuditLog.code_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RedeemAuditLog.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RedeemAuditLog.created_at"`)}
	}
	return nil
}

func (_c *RedeemAuditLogCreate) sqlSave(ctx context.Context) (*RedeemAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemAuditLogCreate) createSpec() (*RedeemAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemauditlog.Table, sqlgraph.NewFieldSpec(redeemauditlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemauditlog.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(redeemauditlog.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(redeemauditlog.FieldActorUserID, field.TypeInt64, value)
		_node.ActorUserID = value
	}
	if value, ok := _c.mutation.BillingSubjectID(); ok {
		_spec.SetField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64, value)
		_node.BillingSubjectID = value
	}
	if value, ok := _c.mutation.CodeType(); ok {
		_spec.SetField(redeemauditlog.FieldCodeType, field.TypeString, value)
		_node.CodeType = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(redeemauditlog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(redeemauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemAuditLog.Create().
//		SetRedeemCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemAuditLogUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *RedeemAuditLogUpsertOne {
	_c.conflict = opts
	return &RedeemAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemAuditLogCreate) OnConflictColumns(columns ...string) *RedeemAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// RedeemAuditLogUpsertOne is the builder for "upsert"-ing
	//  one RedeemAuditLog node.
	RedeemAuditLogUpsertOne struct {
		create *RedeemAuditLogCreate
	}

	// RedeemAuditLogUpsert is the "OnConflict" setter.
	RedeemAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemAuditLogUpsert) SetRedeemCodeID(v int64) *RedeemAuditLogUpsert {
	u.Set(redeemauditlog.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsert) UpdateRedeemCodeID() *RedeemAuditLogUpsert {
	u.SetExcluded(redeemauditlog.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemAuditLogUpsert) AddRedeemCodeID(v int64) *RedeemAuditLogUpsert {
	u.Add(redeemauditlog.FieldRedeemCodeID, v)
	return u
}

// SetCode sets the "code" field.
func (u *RedeemAuditLogUpsert) SetCode(v string) *RedeemAuditLogUpsert {
	u.Set(redeemauditlog.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RedeemAuditLogUpsert) UpdateCode() *RedeemAuditLogUpsert {
	u.SetExcluded(redeemauditlog.FieldCode)
	return u
}

// SetActorUserID sets the "actor_user_id" field.
func (u *RedeemAuditLogUpsert) SetActorUserID(v int64) *RedeemAuditLogUpsert {
	u.Set(redeemauditlog.FieldActorUserID, v)
	return u
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsert) UpdateActorUserID() *RedeemAuditLogUpsert {
	u.SetExcluded(redeemauditlog.FieldActorUserID)
	return u
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *RedeemAuditLogUpsert) AddActorUserID(v int64) *RedeemAuditLogUpsert {
	u.Add(redeemauditlog.FieldActorUserID, v)
	return u
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (u *RedeemAuditLogUpsert) SetBillingSubjectID(v int64) *RedeemAuditLogUpsert {
	u.Set(redeemauditlog.FieldBillingSubjectID, v)
	return u
}

// UpdateBillingSubjectID sets the "billing_subject_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsert) UpdateBillingSubjectID() *RedeemAuditLogUpsert {
	u.SetExcluded(redeemauditlog.FieldBillingSubjectID)
	return u
}

// AddBillingSubjectID adds v to the "billing_subject_id" field.
func (u *RedeemAuditLogUpsert) AddBillingSubjectID(v int64) *RedeemAuditLogUpsert {
	u.Add(redeemauditlog.FieldBillingSubjectID, v)
	return u
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (u *RedeemAuditLogUpsert) ClearBillingSubjectID() *RedeemAuditLogUpsert {
	u.SetNull(redeemauditlog.FieldBillingSubjectID)
	return u
}

// SetCodeType sets the "code_type" field.
func (u *RedeemAuditLogUpsert) SetCodeType(v string) *RedeemAuditLogUpsert {
	u.Set(redeemauditlog.FieldCodeType, v)
	return u
}

// UpdateCodeType sets the "code_type" field to the value that was provided on create.
func (u *RedeemAuditLogUpsert) UpdateCodeType() *RedeemAuditLogUpsert {
	u.SetExcluded(redeemauditlog.FieldCodeType)
	return u
}

// SetAmount sets the "amount" field.
func (u *RedeemAuditLogUpsert) SetAmount(v float64) *RedeemAuditLogUpsert {
	u.Set(redeemauditlog.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RedeemAuditLogUpsert) UpdateAmount() *RedeemAuditLogUpsert {
	u.SetExcluded(redeemauditlog.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RedeemAuditLogUpsert) AddAmount(v float64) *RedeemAuditLogUpsert {
	u.Add(redeemauditlog.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemAuditLogUpsertOne) UpdateNewValues() *RedeemAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(redeemauditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemAuditLogUpsertOne) Ignore() *RedeemAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemAuditLogUpsertOne) DoNothing() *RedeemAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemAuditLogCreate.OnConflict
// documentation for more info.
func (u *RedeemAuditLogUpsertOne) Update(set func(*RedeemAuditLogUpsert)) *RedeemAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemAuditLogUpsertOne) SetRedeemCodeID(v int64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemAuditLogUpsertOne) AddRedeemCodeID(v int64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertOne) UpdateRedeemCodeID() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetCode sets the "code" field.
func (u *RedeemAuditLogUpsertOne) SetCode(v string) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertOne) UpdateCode() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateCode()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *RedeemAuditLogUpsertOne) SetActorUserID(v int64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *RedeemAuditLogUpsertOne) AddActorUserID(v int64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertOne) UpdateActorUserID() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateActorUserID()
	})
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (u *RedeemAuditLogUpsertOne) SetBillingSubjectID(v int64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetBillingSubjectID(v)
	})
}

// AddBillingSubjectID adds v to the "billing_subject_id" field.
func (u *RedeemAuditLogUpsertOne) AddBillingSubjectID(v int64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddBillingSubjectID(v)
	})
}

// UpdateBillingSubjectID sets the "billing_subject_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertOne) UpdateBillingSubjectID() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateBillingSubjectID()
	})
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (u *RedeemAuditLogUpsertOne) ClearBillingSubjectID() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.ClearBillingSubjectID()
	})
}

// SetCodeType sets the "code_type" field.
func (u *RedeemAuditLogUpsertOne) SetCodeType(v string) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetCodeType(v)
	})
}

// UpdateCodeType sets the "code_type" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertOne) UpdateCodeType() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateCodeType()
	})
}

// SetAmount sets the "amount" field.
func (u *RedeemAuditLogUpsertOne) SetAmount(v float64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RedeemAuditLogUpsertOne) AddAmount(v float64) *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertOne) UpdateAmount() *RedeemAuditLogUpsertOne {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *RedeemAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemAuditLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemAuditLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemAuditLogCreateBulk is the builder for creating many RedeemAuditLog entities in bulk.
type RedeemAuditLogCreateBulk struct {
	config
	err      error
	builders []*RedeemAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemAuditLog entities in the database.
func (_c *RedeemAuditLogCreateBulk) Save(ctx context.Context) ([]*RedeemAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemAuditLogCreateBulk) SaveX(ctx context.Context) []*RedeemAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemAuditLogUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemAuditLogUpsertBulk {
	_c.conflict = opts
	return &RedeemAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemAuditLogCreateBulk) OnConflictColumns(columns ...string) *RedeemAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemAuditLogUpsertBulk{
		create: _c,
	}
}

// RedeemAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemAuditLog nodes.
type RedeemAuditLogUpsertBulk struct {
	create *RedeemAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemAuditLogUpsertBulk) UpdateNewValues() *RedeemAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(redeemauditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemAuditLogUpsertBulk) Ignore() *RedeemAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemAuditLogUpsertBulk) DoNothing() *RedeemAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemAuditLogUpsertBulk) Update(set func(*RedeemAuditLogUpsert)) *RedeemAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemAuditLogUpsertBulk) SetRedeemCodeID(v int64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemAuditLogUpsertBulk) AddRedeemCodeID(v int64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertBulk) UpdateRedeemCodeID() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetCode sets the "code" field.
func (u *RedeemAuditLogUpsertBulk) SetCode(v string) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertBulk) UpdateCode() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateCode()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *RedeemAuditLogUpsertBulk) SetActorUserID(v int64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *RedeemAuditLogUpsertBulk) AddActorUserID(v int64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertBulk) UpdateActorUserID() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateActorUserID()
	})
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (u *RedeemAuditLogUpsertBulk) SetBillingSubjectID(v int64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetBillingSubjectID(v)
	})
}

// AddBillingSubjectID adds v to the "billing_subject_id" field.
func (u *RedeemAuditLogUpsertBulk) AddBillingSubjectID(v int64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddBillingSubjectID(v)
	})
}

// UpdateBillingSubjectID sets the "billing_subject_id" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertBulk) UpdateBillingSubjectID() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateBillingSubjectID()
	})
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (u *RedeemAuditLogUpsertBulk) ClearBillingSubjectID() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.ClearBillingSubjectID()
	})
}

// SetCodeType sets the "code_type" field.
func (u *RedeemAuditLogUpsertBulk) SetCodeType(v string) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetCodeType(v)
	})
}

// UpdateCodeType sets the "code_type" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertBulk) UpdateCodeType() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateCodeType()
	})
}

// SetAmount sets the "amount" field.
func (u *RedeemAuditLogUpsertBulk) SetAmount(v float64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RedeemAuditLogUpsertBulk) AddAmount(v float64) *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RedeemAuditLogUpsertBulk) UpdateAmount() *RedeemAuditLogUpsertBulk {
	return u.Update(func(s *RedeemAuditLogUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *RedeemAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
