// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemauditlog"
)

// RedeemAuditLogUpdate is the builder for updating RedeemAuditLog entities.
type RedeemAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemAuditLogMutation
}

// Where appends a list predicates to the RedeemAuditLogUpdate builder.
func (_u *RedeemAuditLogUpdate) Where(ps ...predicate.RedeemAuditLog) *RedeemAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemAuditLogUpdate) SetRedeemCodeID(v int64) *RedeemAuditLogUpdate {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemAuditLogUpdate) SetNillableRedeemCodeID(v *int64) *RedeemAuditLogUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *RedeemAuditLogUpdate) AddRedeemCodeID(v int64) *RedeemAuditLogUpdate {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *RedeemAuditLogUpdate) SetCode(v string) *RedeemAuditLogUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RedeemAuditLogUpdate) SetNillableCode(v *string) *RedeemAuditLogUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *RedeemAuditLogUpdate) SetActorUserID(v int64) *RedeemAuditLogUpdate {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *RedeemAuditLogUpdate) SetNillableActorUserID(v *int64) *RedeemAuditLogUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *RedeemAuditLogUpdate) AddActorUserID(v int64) *RedeemAuditLogUpdate {
	_u.mutation.AddActorUserID(v)
	return _u
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (_u *RedeemAuditLogUpdate) SetBillingSubjectID(v int64) *RedeemAuditLogUpdate {
	_u.mutation.ResetBillingSubjectID()
	_u.mutation.SetBillingSubjectID(v)
	return _u
}

// SetNillableBillingSubjectID sets the "billing_subject_id" field if the given value is not nil.
func (_u *RedeemAuditLogUpdate) SetNillableBillingSubjectID(v *int64) *RedeemAuditLogUpdate {
	if v != nil {
		_u.SetBillingSubjectID(*v)
	}
	return _u
}

// AddBillingSubjectID adds value to the "billing_subject_id" field.
func (_u *RedeemAuditLogUpdate) AddBillingSubjectID(v int64) *RedeemAuditLogUpdate {
	_u.mutation.AddBillingSubjectID(v)
	return _u
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (_u *RedeemAuditLogUpdate) ClearBillingSubjectID() *RedeemAuditLogUpdate {
	_u.mutation.ClearBillingSubjectID()
	return _u
}

// SetCodeType sets the "code_type" field.
func (_u *RedeemAuditLogUpdate) SetCodeType(v string) *RedeemAuditLogUpdate {
	_u.mutation.SetCodeType(v)
	return _u
}

// SetNillableCodeType sets the "code_type" field if the given value is not nil.
func (_u *RedeemAuditLogUpdate) SetNillableCodeType(v *string) *RedeemAuditLogUpdate {
	if v != nil {
		_u.SetCodeType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RedeemAuditLogUpdate) SetAmount(v float64) *RedeemAuditLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RedeemAuditLogUpdate) SetNillableAmount(v *float64) *RedeemAuditLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RedeemAuditLogUpdate) AddAmount(v float64) *RedeemAuditLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// Mutation returns the RedeemAuditLogMutation object of the builder.
func (_u *RedeemAuditLogUpdate) Mutation() *RedeemAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemAuditLogUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := redeemauditlog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RedeemAuditLog.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeType(); ok {
		if err := redeemauditlog.CodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "code_type", err: fmt.Errorf(`ent: validator failed for field "RedeemAuditLog.code_type": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemauditlog.Table, redeemauditlog.Columns, sqlgraph.NewFieldSpec(redeemauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemauditlog.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(redeemauditlog.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(redeemauditlog.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(redeemauditlog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(redeemauditlog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BillingSubjectID(); ok {
		_spec.SetField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBillingSubjectID(); ok {
		_spec.AddField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64, value)
	}
	if _u.mutation.BillingSubjectIDCleared() {
		_spec.ClearField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CodeType(); ok {
		_spec.SetField(redeemauditlog.FieldCodeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(redeemauditlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(redeemauditlog.FieldAmount, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemAuditLogUpdateOne is the builder for updating a single RedeemAuditLog entity.
type RedeemAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemAuditLogMutation
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemAuditLogUpdateOne) SetRedeemCodeID(v int64) *RedeemAuditLogUpdateOne {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemAuditLogUpdateOne) SetNillableRedeemCodeID(v *int64) *RedeemAuditLogUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *RedeemAuditLogUpdateOne) AddRedeemCodeID(v int64) *RedeemAuditLogUpdateOne {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *RedeemAuditLogUpdateOne) SetCode(v string) *RedeemAuditLogUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RedeemAuditLogUpdateOne) SetNillableCode(v *string) *RedeemAuditLogUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *RedeemAuditLogUpdateOne) SetActorUserID(v int64) *RedeemAuditLogUpdateOne {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *RedeemAuditLogUpdateOne) SetNillableActorUserID(v *int64) *RedeemAuditLogUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *RedeemAuditLogUpdateOne) AddActorUserID(v int64) *RedeemAuditLogUpdateOne {
	_u.mutation.AddActorUserID(v)
	return _u
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (_u *RedeemAuditLogUpdateOne) SetBillingSubjectID(v int64) *RedeemAuditLogUpdateOne {
	_u.mutation.ResetBillingSubjectID()
	_u.mutation.SetBillingSubjectID(v)
	return _u
}

// SetNillableBillingSubjectID sets the "billing_subject_id" field if the given value is not nil.
func (_u *RedeemAuditLogUpdateOne) SetNillableBillingSubjectID(v *int64) *RedeemAuditLogUpdateOne {
	if v != nil {
		_u.SetBillingSubjectID(*v)
	}
	return _u
}

// AddBillingSubjectID adds value to the "billing_subject_id" field.
func (_u *RedeemAuditLogUpdateOne) AddBillingSubjectID(v int64) *RedeemAuditLogUpdateOne {
	_u.mutation.AddBillingSubjectID(v)
	return _u
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (_u *RedeemAuditLogUpdateOne) ClearBillingSubjectID() *RedeemAuditLogUpdateOne {
	_u.mutation.ClearBillingSubjectID()
	return _u
}

// SetCodeType sets the "code_type" field.
func (_u *RedeemAuditLogUpdateOne) SetCodeType(v string) *RedeemAuditLogUpdateOne {
	_u.mutation.SetCodeType(v)
	return _u
}

// SetNillableCodeType sets the "code_type" field if the given value is not nil.
func (_u *RedeemAuditLogUpdateOne) SetNillableCodeType(v *string) *RedeemAuditLogUpdateOne {
	if v != nil {
		_u.SetCodeType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RedeemAuditLogUpdateOne) SetAmount(v float64) *RedeemAuditLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RedeemAuditLogUpdateOne) SetNillableAmount(v *float64) *RedeemAuditLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RedeemAuditLogUpdateOne) AddAmount(v float64) *RedeemAuditLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// Mutation returns the RedeemAuditLogMutation object of the builder.
func (_u *RedeemAuditLogUpdateOne) Mutation() *RedeemAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RedeemAuditLogUpdate builder.
func (_u *RedeemAuditLogUpdateOne) Where(ps ...predicate.RedeemAuditLog) *RedeemAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemAuditLogUpdateOne) Select(field string, fields ...string) *RedeemAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemAuditLog entity.
func (_u *RedeemAuditLogUpdateOne) Save(ctx context.Context) (*RedeemAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemAuditLogUpdateOne) SaveX(ctx context.Context) *RedeemAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := redeemauditlog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RedeemAuditLog.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeType(); ok {
		if err := redeemauditlog.CodeTypeValidator(v); err != nil {
			return &ValidationError{Name: "code_type", err: fmt.Errorf(`ent: validator failed for field "RedeemAuditLog.code_type": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *RedeemAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemauditlog.Table, redeemauditlog.Columns, sqlgraph.NewFieldSpec(redeemauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemauditlog.FieldID)
		for _, f := range fields {
			if !redeemauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemauditlog.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(redeemauditlog.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(redeemauditlog.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(redeemauditlog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(redeemauditlog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BillingSubjectID(); ok {
		_spec.SetField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBillingSubjectID(); ok {
		_spec.AddField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64, value)
	}
	if _u.mutation.BillingSubjectIDCleared() {
		_spec.ClearField(redeemauditlog.FieldBillingSubjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CodeType(); ok {
		_spec.SetField(redeemauditlog.FieldCodeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(redeemauditlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(redeemauditlog.FieldAmount, field.TypeFloat64, value)
	}
	_node = &RedeemAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
