// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/billingsubject"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teaminvitation"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamCreate is the builder for creating a Team entity.
type TeamCreate struct {
	config
	mutation *TeamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamCreate) SetCreatedAt(v time.Time) *TeamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamCreate) SetNillableCreatedAt(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamCreate) SetUpdatedAt(v time.Time) *TeamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamCreate) SetNillableUpdatedAt(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TeamCreate) SetDeletedAt(v time.Time) *TeamCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TeamCreate) SetNillableDeletedAt(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TeamCreate) SetName(v string) *TeamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *TeamCreate) SetSlug(v string) *TeamCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *TeamCreate) SetOwnerUserID(v int64) *TeamCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (_c *TeamCreate) SetBillingSubjectID(v int64) *TeamCreate {
	_c.mutation.SetBillingSubjectID(v)
	return _c
}

// SetNillableBillingSubjectID sets the "billing_subject_id" field if the given value is not nil.
func (_c *TeamCreate) SetNillableBillingSubjectID(v *int64) *TeamCreate {
	if v != nil {
		_c.SetBillingSubjectID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamCreate) SetStatus(v string) *TeamCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamCreate) SetNillableStatus(v *string) *TeamCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *TeamCreate) SetAvatarURL(v string) *TeamCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *TeamCreate) SetNillableAvatarURL(v *string) *TeamCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *TeamCreate) SetCreatedByUserID(v int64) *TeamCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *TeamCreate) SetOwnerID(id int64) *TeamCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *TeamCreate) SetOwner(v *User) *TeamCreate {
	return _c.SetOwnerID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *TeamCreate) SetCreatedByID(id int64) *TeamCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *TeamCreate) SetCreatedBy(v *User) *TeamCreate {
	return _c.SetCreatedByID(v.ID)
}

// SetBillingSubject sets the "billing_subject" edge to the BillingSubject entity.
func (_c *TeamCreate) SetBillingSubject(v *BillingSubject) *TeamCreate {
	return _c.SetBillingSubjectID(v.ID)
}

// AddTeamSubjectIDs adds the "team_subject" edge to the BillingSubject entity by IDs.
func (_c *TeamCreate) AddTeamSubjectIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddTeamSubjectIDs(ids...)
	return _c
}

// AddTeamSubject adds the "team_subject" edges to the BillingSubject entity.
func (_c *TeamCreate) AddTeamSubject(v ...*BillingSubject) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamSubjectIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (_c *TeamCreate) AddMemberIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (_c *TeamCreate) AddMembers(v ...*TeamMember) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the TeamInvitation entity by IDs.
func (_c *TeamCreate) AddInvitationIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddInvitationIDs(ids...)
	return _c
}

// AddInvitations adds the "invitations" edges to the TeamInvitation entity.
func (_c *TeamCreate) AddInvitations(v ...*TeamInvitation) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInvitationIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *TeamCreate) AddAPIKeyIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *TeamCreate) AddAPIKeys(v ...*APIKey) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *TeamCreate) AddUsageLogIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *TeamCreate) AddUsageLogs(v ...*UsageLog) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// AddPaymentOrderIDs adds the "payment_orders" edge to the PaymentOrder entity by IDs.
func (_c *TeamCreate) AddPaymentOrderIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddPaymentOrderIDs(ids...)
	return _c
}

// AddPaymentOrders adds the "payment_orders" edges to the PaymentOrder entity.
func (_c *TeamCreate) AddPaymentOrders(v ...*PaymentOrder) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPaymentOrderIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_c *TeamCreate) Mutation() *TeamMutation {
	return _c.mutation
}

// Save creates the Team in the database.
func (_c *TeamCreate) Save(ctx context.Context) (*Team, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamCreate) SaveX(ctx context.Context) *Team {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if team.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := team.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if team.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized team.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := team.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := team.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		v := team.DefaultAvatarURL
		_c.mutation.SetAvatarURL(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Team.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Team.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Team.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Team.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := team.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Team.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Team.owner_user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Team.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := team.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		return &ValidationError{Name: "avatar_url", err: errors.New(`ent: missing required field "Team.avatar_url"`)}
	}
	if _, ok := _c.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "Team.created_by_user_id"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Team.owner"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "Team.created_by"`)}
	}
	return nil
}

func (_c *TeamCreate) sqlSave(ctx context.Context) (*Team, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamCreate) createSpec() (*Team, *sqlgraph.CreateSpec) {
	var (
		_node = &Team{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(team.Table, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(team.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(team.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(team.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(team.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.OwnerTable,
			Columns: []string{team.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.CreatedByTable,
			Columns: []string{team.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BillingSubjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.BillingSubjectTable,
			Columns: []string{team.BillingSubjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billingsubject.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BillingSubjectID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamSubjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.TeamSubjectTable,
			Columns: []string{team.TeamSubjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billingsubject.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembersTable,
			Columns: []string{team.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.InvitationsTable,
			Columns: []string{team.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.APIKeysTable,
			Columns: []string{team.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.UsageLogsTable,
			Columns: []string{team.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentOrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.PaymentOrdersTable,
			Columns: []string{team.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Team.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamCreate) OnConflict(opts ...sql.ConflictOption) *TeamUpsertOne {
	_c.conflict = opts
	return &TeamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamCreate) OnConflictColumns(columns ...string) *TeamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamUpsertOne{
		create: _c,
	}
}

type (
	// TeamUpsertOne is the builder for "upsert"-ing
	//  one Team node.
	TeamUpsertOne struct {
		create *TeamCreate
	}

	// TeamUpsert is the "OnConflict" setter.
	TeamUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamUpsert) SetUpdatedAt(v time.Time) *TeamUpsert {
	u.Set(team.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamUpsert) UpdateUpdatedAt() *TeamUpsert {
	u.SetExcluded(team.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamUpsert) SetDeletedAt(v time.Time) *TeamUpsert {
	u.Set(team.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamUpsert) UpdateDeletedAt() *TeamUpsert {
	u.SetExcluded(team.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamUpsert) ClearDeletedAt() *TeamUpsert {
	u.SetNull(team.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *TeamUpsert) SetName(v string) *TeamUpsert {
	u.Set(team.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsert) UpdateName() *TeamUpsert {
	u.SetExcluded(team.FieldName)
	return u
}

// SetSlug sets the "slug" field.
func (u *TeamUpsert) SetSlug(v string) *TeamUpsert {
	u.Set(team.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TeamUpsert) UpdateSlug() *TeamUpsert {
	u.SetExcluded(team.FieldSlug)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamUpsert) SetOwnerUserID(v int64) *TeamUpsert {
	u.Set(team.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamUpsert) UpdateOwnerUserID() *TeamUpsert {
	u.SetExcluded(team.FieldOwnerUserID)
	return u
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (u *TeamUpsert) SetBillingSubjectID(v int64) *TeamUpsert {
	u.Set(team.FieldBillingSubjectID, v)
	return u
}

// UpdateBillingSubjectID sets the "billing_subject_id" field to the value that was provided on create.
func (u *TeamUpsert) UpdateBillingSubjectID() *TeamUpsert {
	u.SetExcluded(team.FieldBillingSubjectID)
	return u
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (u *TeamUpsert) ClearBillingSubjectID() *TeamUpsert {
	u.SetNull(team.FieldBillingSubjectID)
	return u
}

// SetStatus sets the "status" field.
func (u *TeamUpsert) SetStatus(v string) *TeamUpsert {
	u.Set(team.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamUpsert) UpdateStatus() *TeamUpsert {
	u.SetExcluded(team.FieldStatus)
	return u
}

// SetAvatarURL sets the "avatar_url" field.
func (u *TeamUpsert) SetAvatarURL(v string) *TeamUpsert {
	u.Set(team.FieldAvatarURL, v)
	return u
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *TeamUpsert) UpdateAvatarURL() *TeamUpsert {
	u.SetExcluded(team.FieldAvatarURL)
	return u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *TeamUpsert) SetCreatedByUserID(v int64) *TeamUpsert {
	u.Set(team.FieldCreatedByUserID, v)
	return u
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *TeamUpsert) UpdateCreatedByUserID() *TeamUpsert {
	u.SetExcluded(team.FieldCreatedByUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamUpsertOne) UpdateNewValues() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(team.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamUpsertOne) Ignore() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamUpsertOne) DoNothing() *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamCreate.OnConflict
// documentation for more info.
func (u *TeamUpsertOne) Update(set func(*TeamUpsert)) *TeamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamUpsertOne) SetUpdatedAt(v time.Time) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateUpdatedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamUpsertOne) SetDeletedAt(v time.Time) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateDeletedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamUpsertOne) ClearDeletedAt() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *TeamUpsertOne) SetName(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateName() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateName()
	})
}

// SetSlug sets the "slug" field.
func (u *TeamUpsertOne) SetSlug(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateSlug() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateSlug()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamUpsertOne) SetOwnerUserID(v int64) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateOwnerUserID() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (u *TeamUpsertOne) SetBillingSubjectID(v int64) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetBillingSubjectID(v)
	})
}

// UpdateBillingSubjectID sets the "billing_subject_id" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateBillingSubjectID() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateBillingSubjectID()
	})
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (u *TeamUpsertOne) ClearBillingSubjectID() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.ClearBillingSubjectID()
	})
}

// SetStatus sets the "status" field.
func (u *TeamUpsertOne) SetStatus(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateStatus() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateStatus()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *TeamUpsertOne) SetAvatarURL(v string) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateAvatarURL() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateAvatarURL()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *TeamUpsertOne) SetCreatedByUserID(v int64) *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *TeamUpsertOne) UpdateCreatedByUserID() *TeamUpsertOne {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// Exec executes the query.
func (u *TeamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamCreateBulk is the builder for creating many Team entities in bulk.
type TeamCreateBulk struct {
	config
	err      error
	builders []*TeamCreate
	conflict []sql.ConflictOption
}

// Save creates the Team entities in the database.
func (_c *TeamCreateBulk) Save(ctx context.Context) ([]*Team, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Team, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamCreateBulk) SaveX(ctx context.Context) []*Team {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Team.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamUpsertBulk {
	_c.conflict = opts
	return &TeamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamCreateBulk) OnConflictColumns(columns ...string) *TeamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamUpsertBulk{
		create: _c,
	}
}

// TeamUpsertBulk is the builder for "upsert"-ing
// a bulk of Team nodes.
type TeamUpsertBulk struct {
	create *TeamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamUpsertBulk) UpdateNewValues() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(team.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Team.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamUpsertBulk) Ignore() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamUpsertBulk) DoNothing() *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamCreateBulk.OnConflict
// documentation for more info.
func (u *TeamUpsertBulk) Update(set func(*TeamUpsert)) *TeamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamUpsertBulk) SetUpdatedAt(v time.Time) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateUpdatedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamUpsertBulk) SetDeletedAt(v time.Time) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateDeletedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamUpsertBulk) ClearDeletedAt() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *TeamUpsertBulk) SetName(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateName() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateName()
	})
}

// SetSlug sets the "slug" field.
func (u *TeamUpsertBulk) SetSlug(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateSlug() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateSlug()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamUpsertBulk) SetOwnerUserID(v int64) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateOwnerUserID() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetBillingSubjectID sets the "billing_subject_id" field.
func (u *TeamUpsertBulk) SetBillingSubjectID(v int64) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetBillingSubjectID(v)
	})
}

// UpdateBillingSubjectID sets the "billing_subject_id" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateBillingSubjectID() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateBillingSubjectID()
	})
}

// ClearBillingSubjectID clears the value of the "billing_subject_id" field.
func (u *TeamUpsertBulk) ClearBillingSubjectID() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.ClearBillingSubjectID()
	})
}

// SetStatus sets the "status" field.
func (u *TeamUpsertBulk) SetStatus(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateStatus() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateStatus()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *TeamUpsertBulk) SetAvatarURL(v string) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateAvatarURL() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateAvatarURL()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *TeamUpsertBulk) SetCreatedByUserID(v int64) *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *TeamUpsertBulk) UpdateCreatedByUserID() *TeamUpsertBulk {
	return u.Update(func(s *TeamUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// Exec executes the query.
func (u *TeamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
