// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamMember is the model entity for the TeamMember schema.
type TeamMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int64 `json:"team_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// InvitedByUserID holds the value of the "invited_by_user_id" field.
	InvitedByUserID *int64 `json:"invited_by_user_id,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt *time.Time `json:"joined_at,omitempty"`
	// LastActiveAt holds the value of the "last_active_at" field.
	LastActiveAt *time.Time `json:"last_active_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamMemberQuery when eager-loading is set.
	Edges        TeamMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamMemberEdges holds the relations/edges for other nodes in the graph.
type TeamMemberEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// InvitedBy holds the value of the invited_by edge.
	InvitedBy *User `json:"invited_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamMemberEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// InvitedByOrErr returns the InvitedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamMemberEdges) InvitedByOrErr() (*User, error) {
	if e.InvitedBy != nil {
		return e.InvitedBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "invited_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teammember.FieldID, teammember.FieldTeamID, teammember.FieldUserID, teammember.FieldInvitedByUserID:
			values[i] = new(sql.NullInt64)
		case teammember.FieldRole, teammember.FieldStatus:
			values[i] = new(sql.NullString)
		case teammember.FieldCreatedAt, teammember.FieldUpdatedAt, teammember.FieldDeletedAt, teammember.FieldJoinedAt, teammember.FieldLastActiveAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamMember fields.
func (_m *TeamMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teammember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teammember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teammember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case teammember.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case teammember.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.Int64
			}
		case teammember.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case teammember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case teammember.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case teammember.FieldInvitedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invited_by_user_id", values[i])
			} else if value.Valid {
				_m.InvitedByUserID = new(int64)
				*_m.InvitedByUserID = value.Int64
			}
		case teammember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = new(time.Time)
				*_m.JoinedAt = value.Time
			}
		case teammember.FieldLastActiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_at", values[i])
			} else if value.Valid {
				_m.LastActiveAt = new(time.Time)
				*_m.LastActiveAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamMember.
// This includes values selected through modifiers, order, etc.
func (_m *TeamMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamMember entity.
func (_m *TeamMember) QueryTeam() *TeamQuery {
	return NewTeamMemberClient(_m.config).QueryTeam(_m)
}

// QueryUser queries the "user" edge of the TeamMember entity.
func (_m *TeamMember) QueryUser() *UserQuery {
	return NewTeamMemberClient(_m.config).QueryUser(_m)
}

// QueryInvitedBy queries the "invited_by" edge of the TeamMember entity.
func (_m *TeamMember) QueryInvitedBy() *UserQuery {
	return NewTeamMemberClient(_m.config).QueryInvitedBy(_m)
}

// Update returns a builder for updating this TeamMember.
// Note that you need to call TeamMember.Unwrap() before calling this method if this TeamMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamMember) Update() *TeamMemberUpdateOne {
	return NewTeamMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamMember) Unwrap() *TeamMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamMember) String() string {
	var builder strings.Builder
	builder.WriteString("TeamMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.InvitedByUserID; v != nil {
		builder.WriteString("invited_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.JoinedAt; v != nil {
		builder.WriteString("joined_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastActiveAt; v != nil {
		builder.WriteString("last_active_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TeamMembers is a parsable slice of TeamMember.
type TeamMembers []*TeamMember
