// Code generated by ent, DO NOT EDIT.

package redeemauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the redeemauditlog type in the database.
	Label = "redeem_audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldBillingSubjectID holds the string denoting the billing_subject_id field in the database.
	FieldBillingSubjectID = "billing_subject_id"
	// FieldCodeType holds the string denoting the code_type field in the database.
	FieldCodeType = "code_type"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the redeemauditlog in the database.
	Table = "redeem_audit_logs"
)

// Columns holds all SQL columns for redeemauditlog fields.
var Columns = []string{
	FieldID,
	FieldRedeemCodeID,
	FieldCode,
	FieldActorUserID,
	FieldBillingSubjectID,
	FieldCodeType,
	FieldAmount,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// CodeTypeValidator is a validator for the "code_type" field. It is called by the builders before save.
	CodeTypeValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RedeemAuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByBillingSubjectID orders the results by the billing_subject_id field.
func ByBillingSubjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingSubjectID, opts...).ToFunc()
}

// ByCodeType orders the results by the code_type field.
func ByCodeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeType, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
