// Code generated by ent, DO NOT EDIT.

package redeemauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldID, id))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldRedeemCodeID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldCode, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldActorUserID, v))
}

// BillingSubjectID applies equality check predicate on the "billing_subject_id" field. It's identical to BillingSubjectIDEQ.
func BillingSubjectID(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldBillingSubjectID, v))
}

// CodeType applies equality check predicate on the "code_type" field. It's identical to CodeTypeEQ.
func CodeType(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldCodeType, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldRedeemCodeID, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldContainsFold(FieldCode, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldActorUserID, v))
}

// BillingSubjectIDEQ applies the EQ predicate on the "billing_subject_id" field.
func BillingSubjectIDEQ(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldBillingSubjectID, v))
}

// BillingSubjectIDNEQ applies the NEQ predicate on the "billing_subject_id" field.
func BillingSubjectIDNEQ(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldBillingSubjectID, v))
}

// BillingSubjectIDIn applies the In predicate on the "billing_subject_id" field.
func BillingSubjectIDIn(vs ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldBillingSubjectID, vs...))
}

// BillingSubjectIDNotIn applies the NotIn predicate on the "billing_subject_id" field.
func BillingSubjectIDNotIn(vs ...int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldBillingSubjectID, vs...))
}

// BillingSubjectIDGT applies the GT predicate on the "billing_subject_id" field.
func BillingSubjectIDGT(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldBillingSubjectID, v))
}

// BillingSubjectIDGTE applies the GTE predicate on the "billing_subject_id" field.
func BillingSubjectIDGTE(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldBillingSubjectID, v))
}

// BillingSubjectIDLT applies the LT predicate on the "billing_subject_id" field.
func BillingSubjectIDLT(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldBillingSubjectID, v))
}

// BillingSubjectIDLTE applies the LTE predicate on the "billing_subject_id" field.
func BillingSubjectIDLTE(v int64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldBillingSubjectID, v))
}

// BillingSubjectIDIsNil applies the IsNil predicate on the "billing_subject_id" field.
func BillingSubjectIDIsNil() predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIsNull(FieldBillingSubjectID))
}

// BillingSubjectIDNotNil applies the NotNil predicate on the "billing_subject_id" field.
func BillingSubjectIDNotNil() predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotNull(FieldBillingSubjectID))
}

// CodeTypeEQ applies the EQ predicate on the "code_type" field.
func CodeTypeEQ(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldCodeType, v))
}

// CodeTypeNEQ applies the NEQ predicate on the "code_type" field.
func CodeTypeNEQ(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldCodeType, v))
}

// CodeTypeIn applies the In predicate on the "code_type" field.
func CodeTypeIn(vs ...string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldCodeType, vs...))
}

// CodeTypeNotIn applies the NotIn predicate on the "code_type" field.
func CodeTypeNotIn(vs ...string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldCodeType, vs...))
}

// CodeTypeGT applies the GT predicate on the "code_type" field.
func CodeTypeGT(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldCodeType, v))
}

// CodeTypeGTE applies the GTE predicate on the "code_type" field.
func CodeTypeGTE(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldCodeType, v))
}

// CodeTypeLT applies the LT predicate on the "code_type" field.
func CodeTypeLT(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldCodeType, v))
}

// CodeTypeLTE applies the LTE predicate on the "code_type" field.
func CodeTypeLTE(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldCodeType, v))
}

// CodeTypeContains applies the Contains predicate on the "code_type" field.
func CodeTypeContains(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldContains(FieldCodeType, v))
}

// CodeTypeHasPrefix applies the HasPrefix predicate on the "code_type" field.
func CodeTypeHasPrefix(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldHasPrefix(FieldCodeType, v))
}

// CodeTypeHasSuffix applies the HasSuffix predicate on the "code_type" field.
func CodeTypeHasSuffix(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldHasSuffix(FieldCodeType, v))
}

// CodeTypeEqualFold applies the EqualFold predicate on the "code_type" field.
func CodeTypeEqualFold(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEqualFold(FieldCodeType, v))
}

// CodeTypeContainsFold applies the ContainsFold predicate on the "code_type" field.
func CodeTypeContainsFold(v string) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldContainsFold(FieldCodeType, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemAuditLog) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemAuditLog) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemAuditLog) predicate.RedeemAuditLog {
	return predicate.RedeemAuditLog(sql.NotPredicates(p))
}
