#!/usr/bin/env bash
# Generate a STANDALONE multi-seat Meridian CVM (enclave B) from one seats.json.
#
#   ./gen-seats.sh [seats.json]
#
# Produces (next to this script, all gitignored):
#   compose.seats.generated.yaml    - one Meridian container per subscription seat,
#                                      all in ONE CVM. Each seat gets its own port,
#                                      MERIDIAN_<SEAT>_API_KEY / _PROXY / _CREDENTIALS /
#                                      _CLAUDE_JSON (sealed env), and its own persistent
#                                      /root/.claude volume (token refresh survives restart).
#   route_map.generated.yaml        - sub2api consult.route_map: each model -> all seats
#                                      (rotation + failover). Hot-reloaded by viper.
#   seats.env.template              - the sealed-env KEYS you must fill per seat.
#   register-upstreams.generated.sh - PUTs all seats to the gateway /v1/admin/upstreams
#                                      (reads keys from env; base_url from the CVM app id).
#
# Add an account = add one entry to seats.json, re-run this, then:
#   1) build seats.env from seats.env.template (creds/key/proxy for the NEW seat)
#   2) phala deploy --cvm-id <meridian-cvm> -c compose.seats.generated.yaml -e seats.env
#      (resize the instance as you approach capacity: phala cvms resize <cvm> tdx.xlarge)
#   3) bash register-upstreams.generated.sh   (re-registers ALL seats on the gateway)
#   4) merge route_map.generated.yaml into sub2api config.yaml (viper hot-reloads)
#
# Sizing: one Meridian idles at ~60MB; the real limit is peak concurrency × per-session
# RAM (a busy Claude session can reach ~1GB). We cap both below: MERIDIAN_MAX_CONCURRENT
# (default 3) and NODE_OPTIONS heap (default 1024MB). Budget ~1GB/concurrent session +
# ~0.5GB OS/agent. So: tdx.small/2GB -> 1-2 concurrent, medium/4GB -> 3, large/8GB -> 5-6,
# xlarge/16GB -> ~10 (and ~30 seats). global_oom means you exceeded the CVM's real RAM.
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
SEATS="${1:-$DIR/seats.json}"
command -v jq >/dev/null || { echo "error: jq required"; exit 1; }
[ -f "$SEATS" ] || { echo "error: manifest not found: $SEATS"; exit 1; }

# Meridian image (pin by digest -> measured into the CVM's compose_hash).
IMAGE="docker.io/markerdao/meridian-enclave@sha256:e51d0fd5e51daa846af194977ab2836bf892dfe365fb57977c38514b876d08b8"
# Attestation sidecar image (built from ./attestor). ONE per CVM: all seats share
# this CVM's single dstack identity, so one nonce-bound quote covers them all.
# Pin by digest -> also measured into compose_hash. Public endpoint on :8091.
ATTESTOR_IMAGE="docker.io/markerdao/meridian-attestor@sha256:7e6d51fe173a2762773a9a80a63ff5eee0303a060bc12551bc1fcb30f25056a1"
ATTESTOR_PORT=8091

PORT_BASE=$(jq -r '.meridian_host_port_base // 3456' "$SEATS")
N=$(jq '.seats | length' "$SEATS")
MODELS=$(jq -c '.models' "$SEATS")
[ "$N" -ge 1 ] || { echo "error: no seats in $SEATS"; exit 1; }

COMPOSE="$DIR/compose.seats.generated.yaml"
ROUTEMAP="$DIR/route_map.generated.yaml"
ENVTMPL="$DIR/seats.env.template"
REGISTER="$DIR/register-upstreams.generated.sh"

upper() { echo "$1" | tr '[:lower:]-' '[:upper:]_'; }

# ---- compose (one service per seat) ----
{
  echo "# generated by gen-seats.sh from $(basename "$SEATS") — do not edit by hand"
  echo "# Standalone multi-seat Meridian CVM (enclave B). Deploy:"
  echo "#   phala deploy -n meridian-seats -c compose.seats.generated.yaml -e seats.env"
  echo "services:"
} > "$COMPOSE"

VOLS=""
for i in $(seq 0 $((N-1))); do
  name=$(jq -r ".seats[$i].name" "$SEATS")
  UP=$(upper "$name")
  port=$((PORT_BASE + i))
  {
    echo "  meridian-$name:"
    echo "    image: $IMAGE"
    echo "    ports:"
    echo "      - \"$port:3456\"                              # public endpoint <app-id>-$port.<node>.phala.network"
    echo "    environment:"
    echo "      MERIDIAN_HOST: \"0.0.0.0\""
    echo "      MERIDIAN_PORT: \"3456\""
    echo "      NO_PROXY: \"127.0.0.1,localhost\""
    echo "      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: \"1\"   # silence bundled SDK telemetry"
    echo "      DISABLE_TELEMETRY: \"1\""
    echo "      DISABLE_ERROR_REPORTING: \"1\""
    echo "      # RAM guards (global_oom protection). Safe defaults baked in; tune per-seat via"
    echo "      # sealed env WITHOUT changing compose_hash again. Sized for the CVM's RAM:"
    echo "      #   tdx.small/2GB:1-2  medium/4GB:3  large/8GB:5-6  xlarge/16GB:~10 concurrent."
    echo "      MERIDIAN_MAX_CONCURRENT: \"\${MERIDIAN_${UP}_MAX_CONCURRENT:-3}\"           # cap concurrent Claude sessions/seat"
    echo "      NODE_OPTIONS: \"\${MERIDIAN_${UP}_NODE_OPTIONS:---max-old-space-size=1024}\"   # per-session V8 heap cap (MB)"
    echo "      MERIDIAN_API_KEY: \${MERIDIAN_${UP}_API_KEY:?set MERIDIAN_${UP}_API_KEY (bearer for gateway upstream) via sealed env}"
    echo "      PROXYLITE_SOCKS5: \${MERIDIAN_${UP}_PROXY:-}          # this seat's own static egress IP"
    echo "      # CREDENTIALS/CLAUDE_JSON are OPTIONAL so a RESERVED (not-yet-activated) slot"
    echo "      # boots idle (loggedIn:false, unregistered on the gateway, harmless ~60MB). Since"
    echo "      # these are sealed-env VALUES (not measured text), ACTIVATING a slot = filling them"
    echo "      # via 'phala envs update' — compose_hash is UNCHANGED, so attestation never moves."
    echo "      CLAUDE_CREDENTIALS_JSON: \${MERIDIAN_${UP}_CREDENTIALS:-}"
    echo "      CLAUDE_JSON: \${MERIDIAN_${UP}_CLAUDE_JSON:-}"
    echo "    volumes:"
    echo "      - meridian-$name-claude:/root/.claude          # persist token refresh across restarts"
    echo "    restart: unless-stopped"
  } >> "$COMPOSE"
  VOLS="${VOLS}  meridian-${name}-claude:\n"
done

# ---- attestation sidecar (ONE per CVM; serves the whole CVM's quote) ----
# Public hardware-verification surface: a fresh, nonce-bound TDX DCAP quote +
# dstack event log over CORS at GET /attestation/quote?nonce=<hex>. Carries NO
# secrets / NO prompt content, so no sealed env — keeps the measured compose clean.
{
  echo "  meridian-attestor:"
  echo "    image: $ATTESTOR_IMAGE"
  echo "    ports:"
  echo "      - \"$ATTESTOR_PORT:$ATTESTOR_PORT\"                          # https://<app-id>-$ATTESTOR_PORT.<node>.phala.network/attestation/quote"
  echo "    volumes:"
  echo "      - /var/run/dstack.sock:/var/run/dstack.sock  # dstack 0.5.9 guest-agent (GetQuote)"
  echo "    restart: unless-stopped"
} >> "$COMPOSE"

{ echo "volumes:"; printf "%b" "$VOLS"; } >> "$COMPOSE"

# ---- sub2api route_map (each model -> all seats, rotation+failover) ----
{
  echo "# generated by gen-seats.sh — merge under sub2api config.yaml consult:"
  echo "consult:"
  echo "    route_map:"
  for model in $(echo "$MODELS" | jq -r 'keys[]'); do
    echo "        $model:"
    echo "            format: \"anthropic\""
    echo "            seats:"
    for i in $(seq 0 $((N-1))); do
      echo "                - \"meridian-$(jq -r ".seats[$i].name" "$SEATS")\""
    done
  done
} > "$ROUTEMAP"

# ---- seats.env.template (KEYS only, no secret values) ----
{
  echo "# Fill these per seat, then: phala deploy ... -e seats.env  (this file is gitignored)"
  echo "# Build creds with: jq -c . secrets/<seat>/.credentials.json  and  jq -c . secrets/<seat>/.claude.json"
  for i in $(seq 0 $((N-1))); do
    name=$(jq -r ".seats[$i].name" "$SEATS"); UP=$(upper "$name")
    echo "MERIDIAN_${UP}_API_KEY=mrdn-<unique random hex per seat>"
    echo "MERIDIAN_${UP}_PROXY=$(jq -r ".seats[$i].proxy // \"socks5://<user>:<pass>@<seat static ip>:<port>\"" "$SEATS")"
    echo "MERIDIAN_${UP}_CREDENTIALS=<contents of secrets/$name/.credentials.json>"
    echo "MERIDIAN_${UP}_CLAUDE_JSON=<contents of secrets/$name/.claude.json>"
    echo "# optional RAM guards — compose already bakes safe defaults (MAX_CONCURRENT=3, heap=1024MB);"
    echo "# set these ONLY to override, e.g. down to 1-2 on a tdx.small/2GB CVM. Changing the VALUE"
    echo "# here does NOT change compose_hash (it is sealed-env interpolation, not measured text)."
    echo "#MERIDIAN_${UP}_MAX_CONCURRENT=3           # small/2GB:1-2  medium/4GB:3  large/8GB:5-6  xlarge/16GB:~10"
    echo "#MERIDIAN_${UP}_NODE_OPTIONS=--max-old-space-size=1024"
  done
} > "$ENVTMPL"

# ---- register-upstreams helper (base_url from app id, bearer from env) ----
{
  echo "#!/usr/bin/env bash"
  echo "# generated by gen-seats.sh — register ALL seats on the gateway (full-list PUT)."
  echo "# Requires env: GATEWAY_URL, GATEWAY_ADMIN_TOKEN, MERIDIAN_APP_ID, MERIDIAN_NODE"
  echo "#   (MERIDIAN_NODE e.g. dstack-pha-prod9.phala.network) + each MERIDIAN_<SEAT>_API_KEY."
  echo "set -euo pipefail"
  echo ": \"\${GATEWAY_URL:?}\" \"\${GATEWAY_ADMIN_TOKEN:?}\" \"\${MERIDIAN_APP_ID:?}\" \"\${MERIDIAN_NODE:?}\""
  echo "MODELS='$MODELS'"
  echo "UP='['"
  for i in $(seq 0 $((N-1))); do
    name=$(jq -r ".seats[$i].name" "$SEATS"); UP=$(upper "$name"); port=$((PORT_BASE + i))
    sep=","; [ "$i" -eq 0 ] && sep=""
    echo "UP=\"\$UP$sep{\\\"name\\\":\\\"meridian-$name\\\",\\\"provider\\\":\\\"openai-compatible\\\",\\\"base_url\\\":\\\"https://\${MERIDIAN_APP_ID}-$port.\${MERIDIAN_NODE}\\\",\\\"path\\\":\\\"/v1/messages\\\",\\\"models\\\":\$MODELS,\\\"bearer_token\\\":\\\"\${MERIDIAN_${UP}_API_KEY:?}\\\"}\""
  done
  echo "UP=\"\$UP]\""
  echo "curl -sS -X PUT \"\$GATEWAY_URL/v1/admin/upstreams\" -H \"Authorization: Bearer \$GATEWAY_ADMIN_TOKEN\" -H 'Content-Type: application/json' --data \"\$UP\" -w '\\n[HTTP %{http_code}]\\n'"
} > "$REGISTER"
chmod +x "$REGISTER"

echo "Generated $N seat(s) on ONE CVM (+ 1 meridian-attestor on :$ATTESTOR_PORT):"
echo "  $COMPOSE"
echo "  $ROUTEMAP"
echo "  $ENVTMPL"
echo "  $REGISTER"
echo "Attestation (public, no auth): https://<app-id>-$ATTESTOR_PORT.<node>.phala.network/attestation/quote?nonce=<hex>"
