#!/usr/bin/env bash
# Generate a STANDALONE multi-seat Meridian CVM (enclave B) from one seats.json.
#
#   ./gen-seats.sh [seats.json]
#
# Produces (next to this script, all gitignored):
#   compose.seats.generated.yaml    - one Meridian container per subscription seat,
#                                      all in ONE CVM. Each seat gets its own port,
#                                      MERIDIAN_<SEAT>_API_KEY / _PROXY / _CREDENTIALS /
#                                      _CLAUDE_JSON (sealed env), and its own persistent
#                                      /root/.claude volume (token refresh survives restart).
#   route_map.generated.yaml        - sub2api consult.route_map: each model -> all seats
#                                      (rotation + failover). Hot-reloaded by viper.
#   seats.env.template              - the sealed-env KEYS you must fill per seat.
#   register-upstreams.generated.sh - PUTs all seats to the gateway /v1/admin/upstreams
#                                      (reads keys from env; base_url from the CVM app id).
#
# Add an account = add one entry to seats.json, re-run this, then:
#   1) build seats.env from seats.env.template (creds/key/proxy for the NEW seat)
#   2) phala deploy --cvm-id <meridian-cvm> -c compose.seats.generated.yaml -e seats.env
#      (resize the instance as you approach capacity: phala cvms resize <cvm> tdx.xlarge)
#   3) bash register-upstreams.generated.sh   (re-registers ALL seats on the gateway)
#   4) merge route_map.generated.yaml into sub2api config.yaml (viper hot-reloads)
#
# Sizing: one Meridian idles at ~60MB; the real limit is peak concurrency (default
# MERIDIAN_MAX_CONCURRENT=10/seat). tdx.xlarge (8 vCPU/16GB) comfortably holds ~30 seats.
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
SEATS="${1:-$DIR/seats.json}"
command -v jq >/dev/null || { echo "error: jq required"; exit 1; }
[ -f "$SEATS" ] || { echo "error: manifest not found: $SEATS"; exit 1; }

# Meridian image (pin by digest -> measured into the CVM's compose_hash).
IMAGE="docker.io/markerdao/meridian-enclave@sha256:aaef9917387c41674cf9dc3e85bd117366229fe8299b7aa555f5014f437646c6"

PORT_BASE=$(jq -r '.meridian_host_port_base // 3456' "$SEATS")
N=$(jq '.seats | length' "$SEATS")
MODELS=$(jq -c '.models' "$SEATS")
[ "$N" -ge 1 ] || { echo "error: no seats in $SEATS"; exit 1; }

COMPOSE="$DIR/compose.seats.generated.yaml"
ROUTEMAP="$DIR/route_map.generated.yaml"
ENVTMPL="$DIR/seats.env.template"
REGISTER="$DIR/register-upstreams.generated.sh"

upper() { echo "$1" | tr '[:lower:]-' '[:upper:]_'; }

# ---- compose (one service per seat) ----
{
  echo "# generated by gen-seats.sh from $(basename "$SEATS") — do not edit by hand"
  echo "# Standalone multi-seat Meridian CVM (enclave B). Deploy:"
  echo "#   phala deploy -n meridian-seats -c compose.seats.generated.yaml -e seats.env"
  echo "services:"
} > "$COMPOSE"

VOLS=""
for i in $(seq 0 $((N-1))); do
  name=$(jq -r ".seats[$i].name" "$SEATS")
  UP=$(upper "$name")
  port=$((PORT_BASE + i))
  {
    echo "  meridian-$name:"
    echo "    image: $IMAGE"
    echo "    ports:"
    echo "      - \"$port:3456\"                              # public endpoint <app-id>-$port.<node>.phala.network"
    echo "    environment:"
    echo "      MERIDIAN_HOST: \"0.0.0.0\""
    echo "      MERIDIAN_PORT: \"3456\""
    echo "      NO_PROXY: \"127.0.0.1,localhost\""
    echo "      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: \"1\"   # silence bundled SDK telemetry"
    echo "      DISABLE_TELEMETRY: \"1\""
    echo "      DISABLE_ERROR_REPORTING: \"1\""
    echo "      MERIDIAN_API_KEY: \${MERIDIAN_${UP}_API_KEY:?set MERIDIAN_${UP}_API_KEY (bearer for gateway upstream) via sealed env}"
    echo "      PROXYLITE_SOCKS5: \${MERIDIAN_${UP}_PROXY:-}          # this seat's own static egress IP"
    echo "      CLAUDE_CREDENTIALS_JSON: \${MERIDIAN_${UP}_CREDENTIALS:?set MERIDIAN_${UP}_CREDENTIALS via sealed env}"
    echo "      CLAUDE_JSON: \${MERIDIAN_${UP}_CLAUDE_JSON:?set MERIDIAN_${UP}_CLAUDE_JSON via sealed env}"
    echo "    volumes:"
    echo "      - meridian-$name-claude:/root/.claude          # persist token refresh across restarts"
    echo "    restart: unless-stopped"
  } >> "$COMPOSE"
  VOLS="${VOLS}  meridian-${name}-claude:\n"
done
{ echo "volumes:"; printf "%b" "$VOLS"; } >> "$COMPOSE"

# ---- sub2api route_map (each model -> all seats, rotation+failover) ----
{
  echo "# generated by gen-seats.sh — merge under sub2api config.yaml consult:"
  echo "consult:"
  echo "    route_map:"
  for model in $(echo "$MODELS" | jq -r 'keys[]'); do
    echo "        $model:"
    echo "            format: \"anthropic\""
    echo "            seats:"
    for i in $(seq 0 $((N-1))); do
      echo "                - \"meridian-$(jq -r ".seats[$i].name" "$SEATS")\""
    done
  done
} > "$ROUTEMAP"

# ---- seats.env.template (KEYS only, no secret values) ----
{
  echo "# Fill these per seat, then: phala deploy ... -e seats.env  (this file is gitignored)"
  echo "# Build creds with: jq -c . secrets/<seat>/.credentials.json  and  jq -c . secrets/<seat>/.claude.json"
  for i in $(seq 0 $((N-1))); do
    name=$(jq -r ".seats[$i].name" "$SEATS"); UP=$(upper "$name")
    echo "MERIDIAN_${UP}_API_KEY=mrdn-<unique random hex per seat>"
    echo "MERIDIAN_${UP}_PROXY=$(jq -r ".seats[$i].proxy // \"socks5://<user>:<pass>@<seat static ip>:<port>\"" "$SEATS")"
    echo "MERIDIAN_${UP}_CREDENTIALS=<contents of secrets/$name/.credentials.json>"
    echo "MERIDIAN_${UP}_CLAUDE_JSON=<contents of secrets/$name/.claude.json>"
  done
} > "$ENVTMPL"

# ---- register-upstreams helper (base_url from app id, bearer from env) ----
{
  echo "#!/usr/bin/env bash"
  echo "# generated by gen-seats.sh — register ALL seats on the gateway (full-list PUT)."
  echo "# Requires env: GATEWAY_URL, GATEWAY_ADMIN_TOKEN, MERIDIAN_APP_ID, MERIDIAN_NODE"
  echo "#   (MERIDIAN_NODE e.g. dstack-pha-prod9.phala.network) + each MERIDIAN_<SEAT>_API_KEY."
  echo "set -euo pipefail"
  echo ": \"\${GATEWAY_URL:?}\" \"\${GATEWAY_ADMIN_TOKEN:?}\" \"\${MERIDIAN_APP_ID:?}\" \"\${MERIDIAN_NODE:?}\""
  echo "MODELS='$MODELS'"
  echo "UP='['"
  for i in $(seq 0 $((N-1))); do
    name=$(jq -r ".seats[$i].name" "$SEATS"); UP=$(upper "$name"); port=$((PORT_BASE + i))
    sep=","; [ "$i" -eq 0 ] && sep=""
    echo "UP=\"\$UP$sep{\\\"name\\\":\\\"meridian-$name\\\",\\\"provider\\\":\\\"openai-compatible\\\",\\\"base_url\\\":\\\"https://\${MERIDIAN_APP_ID}-$port.\${MERIDIAN_NODE}\\\",\\\"path\\\":\\\"/v1/messages\\\",\\\"models\\\":\$MODELS,\\\"bearer_token\\\":\\\"\${MERIDIAN_${UP}_API_KEY:?}\\\"}\""
  done
  echo "UP=\"\$UP]\""
  echo "curl -sS -X PUT \"\$GATEWAY_URL/v1/admin/upstreams\" -H \"Authorization: Bearer \$GATEWAY_ADMIN_TOKEN\" -H 'Content-Type: application/json' --data \"\$UP\" -w '\\n[HTTP %{http_code}]\\n'"
} > "$REGISTER"
chmod +x "$REGISTER"

echo "Generated $N seat(s) on ONE CVM:"
echo "  $COMPOSE"
echo "  $ROUTEMAP"
echo "  $ENVTMPL"
echo "  $REGISTER"
