#!/usr/bin/env bash
# Generate all multi-seat config from a single seats.json manifest.
#
#   ./gen-seats.sh [seats.json]
#
# Produces (next to this script):
#   compose.generated.yaml     - one Meridian container per seat (bridge net + host port)
#   upstreams.generated.json   - gateway upstreams entries (meridian-<seat>)
#   route_map.generated.yaml   - sub2api consult.route_map (each model -> seats list)
#
# Adding a seat = add one entry to seats.json, re-run this, then:
#   docker compose -f compose.generated.yaml up -d            # starts only new seats
#   PUT upstreams.generated.json to gateway /v1/admin/upstreams  # hot-reload, no restart
#   merge route_map.generated.yaml into sub2api config.yaml   # hot-reloaded by viper watch
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
SEATS="${1:-$DIR/seats.json}"
command -v jq >/dev/null || { echo "error: jq required"; exit 1; }
[ -f "$SEATS" ] || { echo "error: manifest not found: $SEATS"; exit 1; }

PORT_BASE=$(jq -r '.meridian_host_port_base // 3456' "$SEATS")
N=$(jq '.seats | length' "$SEATS")
MODELS=$(jq -c '.models' "$SEATS")   # { "<public>": "<upstream model>" }

COMPOSE="$DIR/compose.generated.yaml"
UPSTREAMS="$DIR/upstreams.generated.json"
ROUTEMAP="$DIR/route_map.generated.yaml"

# ---- compose ----
{
  echo "# generated by gen-seats.sh from $(basename "$SEATS") — do not edit by hand"
  echo "services:"
} > "$COMPOSE"

up_arr="[]"
for i in $(seq 0 $((N-1))); do
  name=$(jq -r ".seats[$i].name" "$SEATS")
  creds=$(jq -r ".seats[$i].creds_dir" "$SEATS")
  proxy=$(jq -r ".seats[$i].proxy // empty" "$SEATS")
  hostport=$((PORT_BASE + i))
  svc="meridian-$name"
  {
    echo "  $svc:"
    echo "    image: meridian-enclave:dev"
    echo "    restart: unless-stopped"
    echo "    ports:"
    echo "      - \"127.0.0.1:$hostport:3456\""   # host:container; gost 8118 stays per-container
    echo "    environment:"
    echo "      MERIDIAN_HOST: \"0.0.0.0\""
    echo "      MERIDIAN_PORT: \"3456\""
    echo "      NO_PROXY: \"127.0.0.1,localhost\""
    [ -n "$proxy" ] && echo "      PROXYLITE_SOCKS5: \"$proxy\""
    echo "    volumes:"
    echo "      - ./$creds/.credentials.json:/root/.claude/.credentials.json:ro"
    echo "      - ./$creds/.claude.json:/root/.claude.json:ro"
  } >> "$COMPOSE"
  up_arr=$(echo "$up_arr" | jq \
    --arg n "$svc" --arg url "http://127.0.0.1:$hostport" --argjson m "$MODELS" \
    '. + [{name:$n, provider:"openai-compatible", base_url:$url, path:"/v1/messages", models:$m, bearer_token:"x"}]')
done
echo "$up_arr" | jq . > "$UPSTREAMS"

# ---- sub2api route_map (each model -> all seats, anthropic passthrough) ----
{
  echo "# generated by gen-seats.sh — merge under sub2api config.yaml consult:"
  echo "consult:"
  echo "    route_map:"
  for model in $(echo "$MODELS" | jq -r 'keys[]'); do
    echo "        $model:"
    echo "            format: \"anthropic\""
    echo "            seats:"
    for i in $(seq 0 $((N-1))); do
      echo "                - \"meridian-$(jq -r ".seats[$i].name" "$SEATS")\""
    done
  done
} > "$ROUTEMAP"

echo "Generated $N seat(s):"
echo "  $COMPOSE"
echo "  $UPSTREAMS"
echo "  $ROUTEMAP"
