// /proof page copy. NOTE: vue-i18n treats "@" and "|" as special syntax in
// messages — never put digests, emails or shell commands in here; the
// component renders those directly.
export default {
  proof: {
    title: 'Verify this service',
    subtitle:
      'This page proves, in your browser, that the service is running unmodified open-source code inside genuine Intel TDX confidential-computing hardware. Nothing here trusts the server: the cryptographic checks below run locally against Intel and the public source repository.',
    overall: {
      running: 'Verifying live attestation…',
      pass: 'All checks passed — genuine hardware running the published open-source build.',
      fail: 'Verification FAILED — one or more checks did not match. See details below.',
      error: 'Could not complete verification.',
    },
    actions: {
      rerun: 'Re-verify now',
      download: 'Download evidence (JSON)',
    },
    hardware: {
      title: 'Genuine hardware, fresh proof',
      desc: 'A random nonce generated by your browser is bound into a live Intel TDX quote, whose signature chain is verified against Intel collateral — proving real confidential hardware answered just now, not a replay.',
      quoteGenuine: 'TDX quote signature chain (Intel DCAP)',
      tcbStatus: 'Hardware TCB status',
      nonceBinding: 'Freshness: quote is bound to this visit’s nonce',
    },
    measure: {
      title: 'Running exactly the published code',
      desc: 'The hardware-measured event log is replayed and compared against the published reference: the compose file (which pins every container image by digest), the OS image, and the application identity.',
      rtmrReplay: 'Event log authentic (RTMR3 replay matches register)',
      appId: 'Application identity (app-id)',
      composeHash: 'Compose measurement (event log + mr_config_id register)',
      osImageHash: 'OS image measurement',
    },
    source: {
      title: 'Open source, provable build',
      desc: 'The images the measured compose pins are built by public CI from the public repository, signed with keyless cosign and SLSA provenance. Anyone can re-verify the digest-to-commit binding with the command below.',
      repo: 'Source repository',
      commit: 'Pinned commit',
      images: 'Pinned images',
      verifyCmd: 'Third-party verification command',
    },
    disclosure: {
      title: 'What this does not prove (honest scope)',
      body1:
        'Transport: your connection terminates at the Phala gateway in front of the enclave over TLS; this page does not add end-to-end encryption on top of it.',
      body2:
        'Upstream: requests this service forwards to model providers are visible to those providers in plaintext, under their own terms.',
    },
    reference: {
      source: 'Reference source',
      repo: 'published reference (fetched from the public repository, history auditable in git)',
      bakedIn: 'baked-in fallback (could not fetch the repository copy — values may be stale)',
    },
    auditors: {
      title: 'For auditors: every check, raw evidence',
      checks: 'Granular checks',
      raw: 'Raw attestor response',
      refValues: 'Published reference values',
      hint: 'Each row is one independent comparison; informational rows are marked and never faked green.',
      endpoint: 'Attestor endpoint',
      pccs: 'Intel collateral (PCCS)',
    },
    errors: {
      fetchFailed: 'Could not reach the attestor endpoint',
    },
  },
}
